# ตั้ง Cloudflare Tunnel → api.themasterfc.com → localhost:3001 (ครั้งแรกต้อง login browser)
$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $MyInvocation.MyCommand.Path
$TunnelName = "the-master-fc"
$Hostname = "api.themasterfc.com"
$CfDir = Join-Path $env:USERPROFILE ".cloudflared"
$ConfigPath = Join-Path $Root "cloudflared-config.yml"

$env:Path = [System.Environment]::GetEnvironmentVariable("Path", "Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path", "User")
if (-not (Get-Command cloudflared -ErrorAction SilentlyContinue)) {
  Write-Host "[!] ติดตั้ง cloudflared: winget install Cloudflare.cloudflared"
  exit 1
}

Write-Host ""
Write-Host "=== The Master FC — Home Tunnel Setup ==="
Write-Host ""

if (-not (Test-Path (Join-Path $CfDir "cert.pem"))) {
  Write-Host "[1/4] Login Cloudflare (เปิด browser แล้ว authorize)..."
  cloudflared tunnel login
} else {
  Write-Host "[1/4] มี cert.pem แล้ว — ข้าม login"
}

$tunnels = cloudflared tunnel list 2>&1 | Out-String
if ($tunnels -notmatch [regex]::Escape($TunnelName)) {
  Write-Host "[2/4] สร้าง tunnel: $TunnelName"
  cloudflared tunnel create $TunnelName
} else {
  Write-Host "[2/4] tunnel $TunnelName มีอยู่แล้ว"
}

Write-Host "[3/4] ผูก DNS: $Hostname"
cloudflared tunnel route dns $TunnelName $Hostname 2>&1 | Out-Host

$credFile = Get-ChildItem $CfDir -Filter "*.json" -ErrorAction SilentlyContinue |
  Where-Object { $_.Name -ne "config.json" } |
  Sort-Object LastWriteTime -Descending |
  Select-Object -First 1

if (-not $credFile) {
  Write-Host "[ERROR] ไม่พบ credentials JSON ใน $CfDir"
  exit 1
}

@"
# Auto-generated by Setup-Home-Tunnel-Auto.ps1
tunnel: $TunnelName
credentials-file: $($credFile.FullName)

ingress:
  - hostname: $Hostname
    service: http://localhost:3001
  - service: http_status:404
"@ | Set-Content -Path $ConfigPath -Encoding UTF8

Write-Host "[4/4] บันทึก $ConfigPath"
Write-Host ""
Write-Host "เสร็จ — รัน Start-Home-Server.bat + Start-Home-Tunnel.bat คู่กัน"
Write-Host "ทดสอบ: https://$Hostname/health"
Write-Host ""
