/** @type {Record<string, Array<[string, string, number, number, string?]>>} */
export default {
  reddog: [
    ["GK", "Andre Onana", 29, 84, "CM"],
    ["GK", "Altay Bayindir", 26, 76, "TR"],
    ["DF", "Lisandro Martinez", 27, 84, "AR"],
    ["DF", "Harry Maguire", 32, 80, "EN"],
    ["DF", "Luke Shaw", 29, 81, "EN"],
    ["DF", "Diogo Dalot", 25, 82, "PT"],
    ["DF", "Matthijs de Ligt", 25, 84, "NL"],
    ["DF", "Leny Yoro", 19, 78, "FR"],
    ["DF", "Noussair Mazraoui", 27, 81, "MA"],
    ["MF", "Bruno Fernandes", 30, 88, "PT"],
    ["MF", "Casemiro", 32, 85, "BR"],
    ["MF", "Kobbie Mainoo", 19, 80, "EN"],
    ["MF", "Christian Eriksen", 33, 82, "DK"],
    ["MF", "Mason Mount", 26, 81, "EN"],
    ["MF", "Manuel Ugarte", 23, 82, "UY"],
    ["FW", "Marcus Rashford", 27, 84, "EN"],
    ["FW", "Rasmus Hojlund", 22, 82, "DK"],
    ["FW", "Alejandro Garnacho", 20, 81, "AR"],
    ["FW", "Amad Diallo", 22, 78, "CI"],
    ["FW", "Joshua Zirkzee", 23, 79, "NL"],
    ["FW", "Antony", 24, 79, "BR"],
    ["DF", "Tyrell Malacia", 25, 76, "NL"],
    ["MF", "Scott McTominay", 28, 80, "EN"],
  ],
  duckred: [
    ["GK", "Alisson Becker", 32, 89, "BR"],
    ["GK", "Caoimhin Kelleher", 26, 79, "IE"],
    ["DF", "Virgil van Dijk", 33, 89, "NL"],
    ["DF", "Ibrahima Konate", 25, 84, "FR"],
    ["DF", "Andrew Robertson", 30, 85, "SC"],
    ["DF", "Trent Alexander-Arnold", 26, 87, "EN"],
    ["DF", "Joe Gomez", 27, 81, "EN"],
    ["DF", "Konstantinos Tsimikas", 28, 80, "GR"],
    ["DF", "Jarell Quansah", 21, 77, "EN"],
    ["MF", "Alexis Mac Allister", 25, 84, "AR"],
    ["MF", "Dominik Szoboszlai", 24, 83, "HU"],
    ["MF", "Ryan Gravenberch", 22, 80, "NL"],
    ["MF", "Curtis Jones", 23, 79, "EN"],
    ["MF", "Harvey Elliott", 21, 78, "EN"],
    ["MF", "Wataru Endo", 31, 80, "JP"],
    ["FW", "Mohamed Salah", 32, 91, "EG"],
    ["FW", "Darwin Nunez", 25, 83, "UY"],
    ["FW", "Luis Diaz", 27, 84, "CO"],
    ["FW", "Cody Gakpo", 25, 82, "NL"],
    ["FW", "Diogo Jota", 28, 84, "PT"],
    ["FW", "Federico Chiesa", 27, 83, "IT"],
    ["MF", "Tyler Morton", 22, 72, "EN"],
    ["DF", "Rhys Williams", 23, 70, "EN"],
  ],
  hoiblue: [
    ["GK", "Robert Sanchez", 27, 80, "ES"],
    ["GK", "Djordje Petrovic", 25, 78, "RS"],
    ["DF", "Reece James", 25, 84, "EN"],
    ["DF", "Levi Colwill", 22, 81, "EN"],
    ["DF", "Wesley Fofana", 24, 82, "FR"],
    ["DF", "Marc Cucurella", 26, 80, "ES"],
    ["DF", "Malo Gusto", 21, 79, "FR"],
    ["DF", "Axel Disasi", 26, 81, "FR"],
    ["DF", "Trevoh Chalobah", 25, 78, "EN"],
    ["MF", "Enzo Fernandez", 24, 85, "AR"],
    ["MF", "Moises Caicedo", 23, 84, "EC"],
    ["MF", "Conor Gallagher", 24, 82, "EN"],
    ["MF", "Lesley Ugochukwu", 20, 76, "FR"],
    ["MF", "Roméo Lavia", 20, 77, "BE"],
    ["MF", "Carney Chukwuemeka", 21, 76, "EN"],
    ["FW", "Nicolas Jackson", 23, 81, "SN"],
    ["FW", "Christopher Nkunku", 27, 85, "FR"],
    ["FW", "Pedro Neto", 24, 82, "PT"],
    ["FW", "Marc Guiu", 18, 72, "ES"],
    ["FW", "Raheem Sterling", 30, 82, "EN"],
    ["FW", "Mykhailo Mudryk", 23, 79, "UA"],
    ["MF", "Kiernan Dewsbury-Hall", 25, 78, "EN"],
    ["DF", "Benoit Badiashile", 23, 79, "FR"],
  ],
  biggun: [
    ["GK", "David Raya", 29, 84, "ES"],
    ["GK", "Neto", 35, 78, "BR"],
    ["DF", "William Saliba", 24, 87, "FR"],
    ["DF", "Gabriel Magalhaes", 27, 86, "BR"],
    ["DF", "Ben White", 27, 84, "EN"],
    ["DF", "Oleksandr Zinchenko", 28, 81, "UA"],
    ["DF", "Jurrien Timber", 23, 82, "NL"],
    ["DF", "Riccardo Calafiori", 22, 79, "IT"],
    ["DF", "Myles Lewis-Skelly", 18, 74, "EN"],
    ["MF", "Martin Odegaard", 26, 88, "NO"],
    ["MF", "Declan Rice", 26, 87, "EN"],
    ["MF", "Thomas Partey", 31, 84, "GH"],
    ["MF", "Jorginho", 32, 82, "IT"],
    ["MF", "Emile Smith Rowe", 24, 79, "EN"],
    ["MF", "Ethan Nwaneri", 17, 72, "EN"],
    ["FW", "Bukayo Saka", 23, 87, "EN"],
    ["FW", "Gabriel Martinelli", 23, 84, "BR"],
    ["FW", "Kai Havertz", 25, 84, "DE"],
    ["FW", "Leandro Trossard", 30, 82, "BE"],
    ["FW", "Gabriel Jesus", 28, 83, "BR"],
    ["FW", "Raheem Sterling", 30, 82, "EN"],
    ["MF", "Mikel Merino", 28, 83, "ES"],
    ["DF", "Kieran Tierney", 28, 79, "SC"],
  ],
  mooncity: [
    ["GK", "Ederson", 31, 89, "BR"],
    ["GK", "Stefan Ortega", 32, 78, "DE"],
    ["DF", "Ruben Dias", 27, 88, "PT"],
    ["DF", "John Stones", 30, 86, "EN"],
    ["DF", "Kyle Walker", 34, 84, "EN"],
    ["DF", "Josko Gvardiol", 22, 84, "HR"],
    ["DF", "Manuel Akanji", 29, 84, "CH"],
    ["DF", "Rico Lewis", 20, 79, "EN"],
    ["DF", "Nathan Ake", 29, 83, "NL"],
    ["MF", "Rodri", 28, 91, "ES"],
    ["MF", "Kevin De Bruyne", 33, 91, "BE"],
    ["MF", "Bernardo Silva", 30, 88, "PT"],
    ["MF", "Ilkay Gundogan", 34, 85, "DE"],
    ["MF", "Mateo Kovacic", 30, 84, "HR"],
    ["MF", "Phil Foden", 24, 87, "EN"],
    ["FW", "Erling Haaland", 25, 91, "NO"],
    ["FW", "Jeremy Doku", 22, 83, "BE"],
    ["FW", "Jack Grealish", 29, 84, "EN"],
    ["FW", "Savinho", 20, 80, "BR"],
    ["FW", "Oscar Bobb", 21, 76, "NO"],
    ["MF", "Nico O'Reilly", 19, 72, "EN"],
    ["DF", "Abdukodir Khusanov", 20, 75, "UZ"],
    ["MF", "Matheus Nunes", 26, 82, "PT"],
  ],
  lilywhite: [
    ["GK", "Guglielmo Vicario", 27, 84, "IT"],
    ["GK", "Fraser Forster", 36, 75, "EN"],
    ["DF", "Cristian Romero", 26, 86, "AR"],
    ["DF", "Micky van de Ven", 23, 83, "NL"],
    ["DF", "Pedro Porro", 25, 82, "ES"],
    ["DF", "Destiny Udogie", 22, 81, "IT"],
    ["DF", "Ben Davies", 31, 79, "WA"],
    ["DF", "Djed Spence", 24, 77, "EN"],
    ["DF", "Kevin Danso", 26, 78, "AT"],
    ["MF", "James Maddison", 28, 85, "EN"],
    ["MF", "Rodrigo Bentancur", 27, 82, "UY"],
    ["MF", "Yves Bissouma", 28, 82, "ML"],
    ["MF", "Pape Matar Sarr", 22, 79, "SN"],
    ["MF", "Archie Gray", 18, 74, "EN"],
    ["MF", "Lucas Bergvall", 18, 76, "SE"],
    ["FW", "Son Heung-min", 32, 87, "KR"],
    ["FW", "Richarlison", 27, 81, "BR"],
    ["FW", "Dominic Solanke", 27, 82, "EN"],
    ["FW", "Brennan Johnson", 23, 80, "WA"],
    ["FW", "Timo Werner", 28, 80, "DE"],
    ["FW", "Manor Solomon", 25, 78, "IL"],
    ["MF", "Dejan Kulusevski", 24, 82, "SE"],
    ["DF", "Radu Dragusin", 22, 77, "RO"],
  ],
  villalion: [
    ["GK", "Emiliano Martinez", 32, 86, "AR"],
    ["GK", "Marco Bizot", 34, 76, "NL"],
    ["DF", "Matty Cash", 27, 81, "PL"],
    ["DF", "Ezri Konsa", 27, 82, "EN"],
    ["DF", "Pau Torres", 27, 83, "ES"],
    ["DF", "Lucas Digne", 31, 80, "FR"],
    ["DF", "Diego Carlos", 31, 80, "BR"],
    ["DF", "Ian Maatsen", 22, 78, "NL"],
    ["DF", "Tyrone Mings", 31, 79, "EN"],
    ["MF", "Douglas Luiz", 26, 84, "BR"],
    ["MF", "John McGinn", 30, 83, "SC"],
    ["MF", "Leon Bailey", 27, 81, "JM"],
    ["MF", "Youri Tielemans", 27, 83, "BE"],
    ["MF", "Amadou Onana", 23, 81, "BE"],
    ["MF", "Ross Barkley", 30, 78, "EN"],
    ["FW", "Ollie Watkins", 29, 84, "EN"],
    ["FW", "Morgan Rogers", 22, 80, "EN"],
    ["FW", "Jacob Ramsey", 23, 79, "EN"],
    ["FW", "Jhon Duran", 21, 79, "CO"],
    ["FW", "Emiliano Buendia", 27, 80, "AR"],
    ["FW", "Donyell Malen", 25, 81, "NL"],
    ["MF", "Enzo Barrenechea", 23, 75, "AR"],
    ["DF", "Lamare Bogarde", 20, 72, "NL"],
  ],
  magpie: [
    ["GK", "Nick Pope", 32, 84, "EN"],
    ["GK", "Martin Dubravka", 35, 77, "SK"],
    ["DF", "Fabian Schar", 32, 82, "CH"],
    ["DF", "Sven Botman", 24, 82, "NL"],
    ["DF", "Dan Burn", 32, 79, "EN"],
    ["DF", "Tino Livramento", 22, 79, "EN"],
    ["DF", "Lewis Hall", 20, 78, "EN"],
    ["DF", "Emil Krafth", 30, 76, "SE"],
    ["DF", "Jamaal Lascelles", 30, 76, "EN"],
    ["MF", "Bruno Guimaraes", 27, 86, "BR"],
    ["MF", "Joelinton", 28, 82, "BR"],
    ["MF", "Sean Longstaff", 27, 79, "EN"],
    ["MF", "Sandro Tonali", 24, 84, "IT"],
    ["MF", "Jacob Murphy", 29, 79, "EN"],
    ["MF", "Lewis Miley", 18, 74, "EN"],
    ["FW", "Alexander Isak", 25, 86, "SE"],
    ["FW", "Anthony Gordon", 24, 83, "EN"],
    ["FW", "Harvey Barnes", 26, 81, "EN"],
    ["FW", "Callum Wilson", 33, 80, "EN"],
    ["FW", "Yankuba Minteh", 20, 76, "GM"],
    ["FW", "William Osula", 21, 74, "DK"],
    ["MF", "Garang Kuol", 20, 72, "AU"],
    ["DF", "Matt Targett", 28, 77, "EN"],
  ],
  hammer: [
    ["GK", "Alphonse Areola", 31, 80, "FR"],
    ["GK", "Wes Foderingham", 33, 74, "EN"],
    ["DF", "Nayef Aguerd", 28, 81, "MA"],
    ["DF", "Konstantinos Mavropanos", 26, 80, "GR"],
    ["DF", "Aaron Wan-Bissaka", 27, 81, "EN"],
    ["DF", "Emerson", 30, 79, "IT"],
    ["DF", "Maximilian Kilman", 27, 80, "EN"],
    ["DF", "Jean-Clair Todibo", 25, 82, "FR"],
    ["DF", "Aaron Cresswell", 34, 76, "EN"],
    ["MF", "Lucas Paqueta", 27, 84, "BR"],
    ["MF", "James Ward-Prowse", 30, 82, "EN"],
    ["MF", "Tomas Soucek", 29, 82, "CZ"],
    ["MF", "Guido Rodriguez", 30, 81, "AR"],
    ["MF", "Edson Alvarez", 26, 81, "MX"],
    ["MF", "Crysencio Summerville", 23, 78, "NL"],
    ["FW", "Jarrod Bowen", 28, 84, "EN"],
    ["FW", "Niclas Fullkrug", 31, 81, "DE"],
    ["FW", "Maxwel Cornet", 28, 78, "CI"],
    ["FW", "Danny Ings", 32, 76, "EN"],
    ["FW", "Kurt Zouma", 29, 79, "FR"],
    ["FW", "Michail Antonio", 34, 78, "JM"],
    ["MF", "George Earthy", 19, 72, "EN"],
    ["DF", "Kaelan Casey", 20, 70, "EN"],
  ],
  seagull: [
    ["GK", "Bart Verbruggen", 22, 78, "NL"],
    ["GK", "Jason Steele", 34, 74, "EN"],
    ["DF", "Lewis Dunk", 33, 81, "EN"],
    ["DF", "Igor Julio", 26, 78, "BR"],
    ["DF", "Joel Veltman", 32, 78, "NL"],
    ["DF", "Pervis Estupinan", 26, 81, "EC"],
    ["DF", "Jan Paul van Hecke", 24, 78, "NL"],
    ["DF", "Olivier Boscagli", 27, 79, "FR"],
    ["DF", "Ferdi Kadioglu", 24, 78, "TR"],
    ["MF", "Pascal Gross", 33, 82, "DE"],
    ["MF", "Carlos Baleba", 20, 78, "CM"],
    ["MF", "Matt O'Riley", 24, 80, "DK"],
    ["MF", "Yankuba Minteh", 20, 76, "GM"],
    ["MF", "Julio Enciso", 21, 78, "PY"],
    ["MF", "Jack Hinshelwood", 19, 76, "EN"],
    ["FW", "Danny Welbeck", 34, 78, "EN"],
    ["FW", "Georginio Rutter", 22, 79, "FR"],
    ["FW", "Kaoru Mitoma", 27, 82, "JP"],
    ["FW", "Simon Adingra", 22, 78, "CI"],
    ["FW", "Stefanos Tzimas", 18, 72, "GR"],
    ["FW", "Facundo Buonanotte", 20, 76, "AR"],
    ["MF", "Adam Webster", 29, 77, "EN"],
    ["DF", "Maxim De Cuyper", 24, 75, "BE"],
  ],
  wolfpack: [
    ["GK", "Jose Sa", 31, 80, "PT"],
    ["GK", "Sam Johnstone", 31, 77, "EN"],
    ["DF", "Max Kilman", 27, 80, "EN"],
    ["DF", "Craig Dawson", 34, 77, "EN"],
    ["DF", "Matt Doherty", 32, 77, "IE"],
    ["DF", "Nelson Semedo", 30, 79, "PT"],
    ["DF", "Toti Gomes", 25, 78, "PT"],
    ["DF", "Emmanuel Agbadou", 27, 78, "CI"],
    ["DF", "Santiago Bueno", 25, 77, "UY"],
    ["MF", "Matheus Cunha", 25, 83, "BR"],
    ["MF", "Joao Gomes", 23, 79, "BR"],
    ["MF", "Andre", 25, 80, "BR"],
    ["MF", "Tommy Doyle", 23, 76, "EN"],
    ["MF", "Marshall Munetsi", 28, 78, "ZW"],
    ["MF", "Boubacar Traore", 23, 75, "ML"],
    ["FW", "Hwang Hee-chan", 28, 81, "KR"],
    ["FW", "Jorgen Strand Larsen", 24, 79, "NO"],
    ["FW", "Fábio Silva", 22, 76, "PT"],
    ["FW", "Saša Kalajdžić", 27, 77, "AT"],
    ["FW", "Leon Chiwome", 18, 70, "EN"],
    ["FW", "Nathan Fraser", 19, 71, "IE"],
    ["MF", "Enso Gonzalez", 20, 72, "PY"],
    ["DF", "Alfie Pond", 20, 68, "EN"],
  ],
  toffee: [
    ["GK", "Jordan Pickford", 30, 84, "EN"],
    ["GK", "Asmir Begovic", 37, 73, "BA"],
    ["DF", "James Tarkowski", 32, 82, "EN"],
    ["DF", "Jarrad Branthwaite", 22, 81, "EN"],
    ["DF", "Vitalii Mykolenko", 25, 79, "UA"],
    ["DF", "Nathan Patterson", 23, 77, "SC"],
    ["DF", "Ashley Young", 39, 74, "EN"],
    ["DF", "Jake O'Brien", 23, 76, "IE"],
    ["DF", "Michael Keane", 31, 77, "EN"],
    ["MF", "Abdoulaye Doucoure", 31, 80, "ML"],
    ["MF", "Idrissa Gueye", 34, 80, "SN"],
    ["MF", "James Garner", 23, 78, "EN"],
    ["MF", "Tim Iroegbunam", 21, 75, "EN"],
    ["MF", "Amadou Onana", 23, 81, "BE"],
    ["MF", "Dele Alli", 28, 76, "EN"],
    ["FW", "Dominic Calvert-Lewin", 27, 80, "EN"],
    ["FW", "Beto", 26, 78, "PT"],
    ["FW", "Iliman Ndiaye", 24, 79, "SN"],
    ["FW", "Armando Broja", 23, 77, "AL"],
    ["FW", "Dwight McNeil", 24, 79, "EN"],
    ["FW", "Chermiti", 21, 73, "PT"],
    ["MF", "Tyler Onyango", 21, 72, "EN"],
    ["DF", "Reece Welch", 20, 70, "EN"],
  ],
  forest: [
    ["GK", "Matz Sels", 32, 80, "BE"],
    ["GK", "Wayne Hennessey", 37, 72, "WA"],
    ["DF", "Murillo", 22, 80, "BR"],
    ["DF", "Willy Boly", 33, 77, "CI"],
    ["DF", "Neco Williams", 23, 78, "WA"],
    ["DF", "Ola Aina", 27, 77, "NG"],
    ["DF", "Harry Toffolo", 29, 76, "EN"],
    ["DF", "Nikola Milenkovic", 26, 80, "RS"],
    ["DF", "Morato", 23, 77, "BR"],
    ["MF", "Morgan Gibbs-White", 24, 82, "EN"],
    ["MF", "Ibrahim Sangare", 26, 82, "CI"],
    ["MF", "Danilo", 23, 79, "BR"],
    ["MF", "Elliot Anderson", 22, 78, "EN"],
    ["MF", "Nicolas Dominguez", 26, 78, "AR"],
    ["MF", "Ryan Yates", 26, 77, "EN"],
    ["FW", "Chris Wood", 32, 80, "NZ"],
    ["FW", "Callum Hudson-Odoi", 23, 78, "EN"],
    ["FW", "Taiwo Awoniyi", 27, 78, "NG"],
    ["FW", "Anthony Elanga", 22, 78, "SE"],
    ["FW", "Jota Silva", 25, 76, "PT"],
    ["FW", "Igor Jesus", 23, 75, "BR"],
    ["MF", "Marko Stamenic", 22, 73, "NZ"],
    ["DF", "Zach Abbott", 18, 70, "EN"],
  ],
  eagle: [
    ["GK", "Dean Henderson", 27, 80, "EN"],
    ["GK", "Remi Matthews", 30, 72, "EN"],
    ["DF", "Marc Guehi", 24, 82, "EN"],
    ["DF", "Maxence Lacroix", 24, 81, "FR"],
    ["DF", "Daniel Munoz", 28, 80, "CO"],
    ["DF", "Trevoh Chalobah", 25, 78, "EN"],
    ["DF", "Chris Richards", 24, 78, "US"],
    ["DF", "Nathaniel Clyne", 33, 75, "EN"],
    ["DF", "Benjamin Whiteman", 27, 74, "EN"],
    ["MF", "Adam Wharton", 20, 80, "EN"],
    ["MF", "Eberechi Eze", 26, 84, "EN"],
    ["MF", "Daichi Kamada", 28, 80, "JP"],
    ["MF", "Jefferson Lerma", 30, 79, "CO"],
    ["MF", "Will Hughes", 29, 77, "EN"],
    ["MF", "Naouirou Ahamada", 22, 75, "FR"],
    ["FW", "Jean-Philippe Mateta", 27, 80, "FR"],
    ["FW", "Ismaila Sarr", 26, 80, "SN"],
    ["FW", "Eddie Nketiah", 25, 78, "EN"],
    ["FW", "Franco Umeh", 19, 72, "IE"],
    ["FW", "Odsonne Edouard", 26, 77, "FR"],
    ["FW", "Matheus Franca", 20, 74, "BR"],
    ["MF", "Justin Devenny", 20, 71, "NI"],
    ["DF", "Caleb Richards", 22, 70, "EN"],
  ],
  bee: [
    ["GK", "Mark Flekken", 31, 79, "NL"],
    ["GK", "Hakon Valdimarsson", 23, 72, "IS"],
    ["DF", "Ethan Pinnock", 31, 79, "JM"],
    ["DF", "Nathan Collins", 23, 80, "IE"],
    ["DF", "Rico Henry", 27, 78, "EN"],
    ["DF", "Kristoffer Ajer", 26, 78, "NO"],
    ["DF", "Mads Roerslev", 25, 76, "DK"],
    ["DF", "Sepp van den Berg", 22, 76, "NL"],
    ["DF", "Michael Kayode", 20, 74, "IT"],
    ["MF", "Christian Norgaard", 30, 81, "DK"],
    ["MF", "Mathias Jensen", 28, 79, "DK"],
    ["MF", "Mikkel Damsgaard", 24, 79, "DK"],
    ["MF", "Frank Onyeka", 26, 77, "NG"],
    ["MF", "Yehor Yarmoliuk", 20, 74, "UA"],
    ["MF", "Vitaly Janelt", 26, 77, "DE"],
    ["FW", "Bryan Mbeumo", 25, 83, "CM"],
    ["FW", "Yoane Wissa", 28, 80, "CD"],
    ["FW", "Kevin Schade", 22, 78, "DE"],
    ["FW", "Igor Thiago", 23, 76, "BR"],
    ["FW", "Fabio Carvalho", 22, 77, "PT"],
    ["FW", "Thiago", 24, 75, "BR"],
    ["MF", "Paris Maghoma", 23, 72, "EN"],
    ["DF", "Benjamin Arthur", 19, 68, "EN"],
  ],
  cherry: [
    ["GK", "Kepa Arrizabalaga", 30, 80, "ES"],
    ["GK", "Neto", 35, 76, "BR"],
    ["DF", "Marcos Senesi", 27, 79, "AR"],
    ["DF", "Lloyd Kelly", 26, 78, "EN"],
    ["DF", "Adam Smith", 33, 74, "EN"],
    ["DF", "Chris Mepham", 27, 75, "WA"],
    ["DF", "Julian Araujo", 23, 75, "MX"],
    ["DF", "Milos Kerkez", 21, 78, "HU"],
    ["DF", "Dean Huijsen", 19, 76, "ES"],
    ["MF", "Ryan Christie", 29, 78, "SC"],
    ["MF", "Philip Billing", 28, 78, "DK"],
    ["MF", "Alex Scott", 21, 77, "EN"],
    ["MF", "Lewis Cook", 27, 77, "EN"],
    ["MF", "Tyler Adams", 25, 79, "US"],
    ["MF", "David Brooks", 27, 77, "WA"],
    ["FW", "Antoine Semenyo", 25, 79, "GH"],
    ["FW", "Evanilson", 25, 78, "BR"],
    ["FW", "Luis Sinisterra", 25, 78, "CO"],
    ["FW", "Justin Kluivert", 25, 77, "NL"],
    ["FW", "Enes Unal", 27, 77, "TR"],
    ["FW", "Daniel Jebbison", 21, 74, "CA"],
    ["MF", "Ben Winterburn", 19, 71, "EN"],
    ["DF", "Zain Silcott-Duberry", 19, 70, "EN"],
  ],
};
