/** @type {Record<string, Array<[string, string, number, number, string?]>>} */
export default {
  porto: [
    ["GK", "Diogo Costa", 25, 86, "PT"],
    ["GK", "Claudio Ramos", 33, 76, "PT"],
    ["GK", "Goncalo Borges", 23, 72, "PT"],
    ["DF", "Pepe", 41, 80, "PT"],
    ["DF", "Joao Mario", 24, 79, "PT"],
    ["DF", "Wendell", 30, 78, "BR"],
    ["DF", "Otavio", 27, 78, "PT"],
    ["DF", "Fabio Cardoso", 30, 77, "PT"],
    ["DF", "Zaidu Sanusi", 27, 76, "NG"],
    ["DF", "Martim Fernandes", 19, 74, "PT"],
    ["DF", "Dorival", 22, 73, "BR"],
    ["MF", "Alan Varela", 23, 80, "AR"],
    ["MF", "Pepê", 27, 81, "BR"],
    ["MF", "Galeno", 27, 82, "BR"],
    ["MF", "Stephen Eustáquio", 27, 79, "CA"],
    ["MF", "Nico Gonzalez", 22, 79, "ES"],
    ["MF", "Marko Grujic", 28, 78, "RS"],
    ["MF", "Andre Franco", 27, 77, "PT"],
    ["MF", "Vasquez", 24, 76, "CO"],
    ["FW", "Samu Omorodion", 20, 78, "ES"],
    ["FW", "Evanilson", 24, 80, "BR"],
    ["FW", "Francisco Conceição", 21, 78, "PT"],
    ["FW", "Deniz Gul", 19, 72, "TR"],
  ],
  benfica: [
    ["GK", "Anatoliy Trubin", 23, 82, "UA"],
    ["GK", "Samuel Soares", 21, 74, "PT"],
    ["GK", "Andreas Samaris", 35, 72, "GR"],
    ["DF", "Nicolas Otamendi", 36, 83, "AR"],
    ["DF", "Antonio Silva", 21, 82, "PT"],
    ["DF", "Alvaro Carreras", 21, 79, "ES"],
    ["DF", "Morato", 23, 78, "BR"],
    ["DF", "Tomás Araújo", 22, 77, "PT"],
    ["DF", "Gilberto", 31, 76, "PT"],
    ["MF", "Florentino", 25, 80, "PT"],
    ["MF", "Orkun Kokcu", 24, 82, "TR"],
    ["MF", "Fredrik Aursnes", 28, 81, "NO"],
    ["MF", "Manu Silva", 21, 78, "PT"],
    ["MF", "Leandro Barreiro", 24, 78, "LU"],
    ["MF", "Renato Sanches", 27, 79, "PT"],
    ["MF", "Joao Neves", 20, 84, "PT"],
    ["FW", "Angel Di Maria", 36, 84, "AR"],
    ["FW", "Vangelis Pavlidis", 26, 82, "GR"],
    ["FW", "Rafa Silva", 31, 83, "PT"],
    ["FW", "Arthur Cabral", 26, 79, "BR"],
    ["FW", "Andreas Schjelderup", 20, 76, "NO"],
    ["FW", "Gianluca Prestianni", 18, 74, "AR"],
    ["FW", "Marcos Leonardo", 21, 77, "BR"],
  ],
  sporting: [
    ["GK", "Rui Patricio", 36, 80, "PT"],
    ["GK", "Franco Israel", 24, 76, "UY"],
    ["GK", "Joao Virgilia", 22, 72, "PT"],
    ["DF", "Sebastian Coates", 33, 80, "UY"],
    ["DF", "Goncalo Inacio", 23, 82, "PT"],
    ["DF", "Ousmane Diomande", 20, 81, "CI"],
    ["DF", "Ricardo Esgaio", 31, 78, "PT"],
    ["DF", "Matheus Reis", 29, 77, "BR"],
    ["DF", "Zeno Debast", 21, 76, "BE"],
    ["DF", "Nuno Santos", 23, 76, "PT"],
    ["MF", "Morten Hjulmand", 24, 83, "DK"],
    ["MF", "Geny Catamo", 23, 79, "MZ"],
    ["MF", "Daniel Braganca", 25, 77, "PT"],
    ["MF", "Hidemasa Morita", 29, 79, "JP"],
    ["MF", "Pedro Goncalves", 26, 82, "PT"],
    ["MF", "Pote", 24, 78, "PT"],
    ["MF", "Maximiliano Araujo", 25, 77, "UY"],
    ["FW", "Viktor Gyokeres", 26, 86, "SE"],
    ["FW", "Francisco Trincao", 25, 80, "PT"],
    ["FW", "Marcus Edwards", 25, 79, "EN"],
    ["FW", "Paulinho", 23, 78, "PT"],
    ["FW", "Geovany Quenda", 17, 74, "PT"],
    ["FW", "Conrad Harder", 19, 75, "DK"],
  ],
  braga: [
    ["GK", "Matheus", 32, 79, "BR"],
    ["GK", "Lucas Hornung", 23, 72, "BR"],
    ["GK", "Tiago Sa", 27, 71, "PT"],
    ["DF", "Sikou Niakate", 25, 77, "ML"],
    ["DF", "Vitor Tormena", 28, 76, "BR"],
    ["DF", "Paulo Oliveira", 32, 75, "PT"],
    ["DF", "Joao Ferreira", 23, 74, "PT"],
    ["DF", "Borja Sainz", 23, 76, "ES"],
    ["DF", "Fabiano Silva", 24, 74, "BR"],
    ["MF", "Ricardo Horta", 30, 80, "PT"],
    ["MF", "Andre Horta", 28, 78, "PT"],
    ["MF", "Al Musrati", 28, 79, "LY"],
    ["MF", "Jean-Baptiste Gorby", 23, 76, "FR"],
    ["MF", "Rodrigo Zalazar", 25, 77, "UY"],
    ["MF", "Martim Neto", 21, 74, "PT"],
    ["MF", "Gabriel Martínez", 22, 73, "AR"],
    ["MF", "Vitor Carvalho", 26, 75, "PT"],
    ["FW", "Bruma", 30, 78, "PT"],
    ["FW", "Roberto Fernandez", 22, 77, "PY"],
    ["FW", "Franz Magalhaes", 21, 74, "BR"],
    ["FW", "Alvaro Djalo", 24, 76, "PT"],
    ["FW", "Roger Fernandes", 19, 73, "PT"],
    ["FW", "Ismael Gharbi", 20, 74, "TN"],
  ],
  guimaraes: [
    ["GK", "Charles", 29, 76, "BR"],
    ["GK", "Bruno Varela", 29, 74, "PT"],
    ["GK", "Ruben", 22, 70, "PT"],
    ["DF", "Jorge Fernandes", 27, 75, "PT"],
    ["DF", "Rui Santos", 24, 74, "PT"],
    ["DF", "Maga", 26, 73, "PT"],
    ["DF", "Tiago Silva", 27, 74, "PT"],
    ["DF", "Bruno Gaspar", 31, 73, "PT"],
    ["DF", "Joao Mendes", 22, 72, "PT"],
    ["DF", "Alexandre Silva", 27, 71, "PT"],
    ["MF", "Samu Oliveira", 27, 76, "PT"],
    ["MF", "Telmo Arcanjo", 24, 74, "PT"],
    ["MF", "Beni", 22, 73, "PT"],
    ["MF", "Anderson Silva", 25, 74, "BR"],
    ["MF", "Manu Silva", 25, 73, "PT"],
    ["MF", "Alhassan Yusuf", 24, 74, "NG"],
    ["MF", "Benjamin Bouchouari", 24, 73, "BE"],
    ["FW", "Nelson Oliveira", 32, 75, "PT"],
    ["FW", "Gustavo Silva", 23, 73, "PT"],
    ["FW", "Sam Órfão", 24, 72, "PT"],
    ["FW", "Rafa Silva", 22, 71, "PT"],
    ["FW", "Bryan Mendez", 21, 70, "CO"],
    ["FW", "Jefferson", 26, 72, "BR"],
  ],
  boavista: [
    ["GK", "Bruno Ferreira", 28, 74, "PT"],
    ["GK", "Joao Goncalves", 24, 70, "PT"],
    ["GK", "Cesar", 35, 68, "PT"],
    ["DF", "Bruno Onyemaechi", 26, 73, "NG"],
    ["DF", "Lucas Rocha", 24, 72, "PT"],
    ["DF", "Joao Marcelo", 22, 71, "PT"],
    ["DF", "Rebocho", 29, 72, "PT"],
    ["DF", "Malcolm Barcola", 25, 71, "FR"],
    ["DF", "Cesar Peixoto", 23, 70, "PT"],
    ["DF", "Pedro Malheiro", 25, 71, "PT"],
    ["MF", "Ilija Vukotic", 28, 74, "ME"],
    ["MF", "Gaius Makouta", 27, 73, "CG"],
    ["MF", "Luís Freitas", 24, 72, "PT"],
    ["MF", "Petar Musa", 26, 73, "BA"],
    ["MF", "Alanzinho", 24, 71, "PT"],
    ["MF", "Tiago Morais", 22, 70, "PT"],
    ["MF", "Bruno Lourenco", 26, 69, "PT"],
    ["FW", "Robert Bozenik", 24, 73, "SK"],
    ["FW", "Rafael Braga", 23, 71, "PT"],
    ["FW", "Jesper Larsen", 26, 72, "DK"],
    ["FW", "Yusupha Njie", 25, 72, "GM"],
    ["FW", "Malcom Bokele", 24, 69, "CM"],
    ["FW", "Yannick", 26, 68, "CI"],
  ],
  famalicao: [
    ["GK", "Andrew", 30, 74, "BR"],
    ["GK", "Zé Pedro", 24, 70, "PT"],
    ["GK", "Rui Silva", 23, 67, "PT"],
    ["DF", "Riccieli", 28, 73, "BR"],
    ["DF", "Leonardo", 24, 72, "BR"],
    ["DF", "Pedro Chaves", 25, 71, "PT"],
    ["DF", "Santiago Colombatto", 27, 72, "AR"],
    ["DF", "Vitorino Antunes", 37, 71, "PT"],
    ["DF", "Gustavo Lopes", 22, 70, "PT"],
    ["MF", "Gustavo Assuncao", 24, 72, "PT"],
    ["MF", "Iván Jaime", 25, 73, "ES"],
    ["MF", "Gustavo Sa", 26, 72, "PT"],
    ["MF", "Ozz Bilal", 24, 71, "PT"],
    ["MF", "Bruno Jordao", 25, 70, "PT"],
    ["MF", "Pedro Figueiredo", 25, 69, "PT"],
    ["MF", "Joao Neves", 22, 68, "PT"],
    ["FW", "Joao Rodrigues", 25, 73, "PT"],
    ["FW", "Gil Dias", 28, 72, "PT"],
    ["FW", "Jonathan Rodriguez", 30, 71, "UY"],
    ["FW", "Pablo", 24, 70, "BR"],
    ["FW", "Rafael Barbosa", 21, 68, "PT"],
    ["FW", "Bruno Silva", 25, 67, "PT"],
    ["FW", "Joao Silva", 22, 66, "PT"],
  ],
  rioave: [
    ["GK", "Jhonatan", 28, 73, "BR"],
    ["GK", "Diogo Silva", 24, 69, "PT"],
    ["GK", "Tiago Ferreira", 24, 66, "PT"],
    ["DF", "Marcelo", 28, 72, "BR"],
    ["DF", "Jorge Pereira", 25, 71, "PT"],
    ["DF", "Costinha", 26, 70, "PT"],
    ["DF", "Fabiano Silva", 24, 70, "PT"],
    ["DF", "Angel Zapata", 22, 68, "CO"],
    ["DF", "Patrick", 26, 67, "BR"],
    ["DF", "Aderlan", 32, 66, "BR"],
    ["MF", "Joca", 28, 73, "PT"],
    ["MF", "Goncalo Rodrigues", 24, 71, "PT"],
    ["MF", "Luís Gustavo", 26, 70, "BR"],
    ["MF", "Andre Luiz", 25, 69, "BR"],
    ["MF", "Guga", 26, 68, "PT"],
    ["MF", "Oleksandr Petrov", 25, 67, "UA"],
    ["MF", "Joao Carvalho", 27, 66, "PT"],
    ["FW", "Clayton", 24, 72, "BR"],
    ["FW", "Nikola Milosevic", 26, 71, "RS"],
    ["FW", "Ukra", 28, 70, "PT"],
    ["FW", "Renato Santos", 23, 68, "PT"],
    ["FW", "Bruno Silva", 24, 66, "PT"],
    ["FW", "Luizao", 28, 65, "BR"],
  ],
  estoril: [
    ["GK", "Francisco Ramos", 27, 72, "PT"],
    ["GK", "Pedro Silva", 22, 68, "PT"],
    ["GK", "Tiago Sousa", 23, 65, "PT"],
    ["DF", "Tiago Ferrao", 26, 71, "PT"],
    ["DF", "Bernardo Vital", 24, 70, "PT"],
    ["DF", "Pedro Braga", 25, 69, "PT"],
    ["DF", "Joao Vitor", 23, 68, "PT"],
    ["DF", "Carlos Eduardo", 26, 67, "BR"],
    ["DF", "Fabio Cardoso", 24, 66, "PT"],
    ["MF", "Goncalo Franco", 25, 72, "PT"],
    ["MF", "Joao Carvalho", 27, 71, "PT"],
    ["MF", "Michel", 28, 70, "BR"],
    ["MF", "Xeka", 29, 69, "PT"],
    ["MF", "Joao Talocha", 26, 68, "PT"],
    ["MF", "Tiago Gouveia", 23, 67, "PT"],
    ["MF", "Pedro Amador", 25, 66, "PT"],
    ["FW", "Alemao", 26, 72, "BR"],
    ["FW", "Yanis Begraoui", 22, 71, "MA"],
    ["FW", "Andrea Cambiaso", 24, 70, "IT"],
    ["FW", "Joelinton Caju", 24, 69, "BR"],
    ["FW", "Giovani", 28, 68, "BR"],
    ["FW", "Goncalo Rodrigues", 23, 67, "PT"],
    ["FW", "Fabio Silva", 22, 65, "PT"],
  ],
  arouca: [
    ["GK", "Tiago Ferreira", 26, 71, "PT"],
    ["GK", "Bruno Nunes", 25, 67, "PT"],
    ["GK", "Rui Silva", 22, 64, "PT"],
    ["DF", "Thiago Silva", 25, 70, "PT"],
    ["DF", "Jason", 26, 69, "BR"],
    ["DF", "David Moutinho", 24, 68, "PT"],
    ["DF", "Bruno Antunes", 27, 67, "PT"],
    ["DF", "Pedro Silva", 23, 66, "PT"],
    ["DF", "Quina", 25, 65, "PT"],
    ["MF", "David Simao", 30, 71, "PT"],
    ["MF", "Eduardo Borges", 24, 69, "PT"],
    ["MF", "Taichi Fukui", 21, 68, "JP"],
    ["MF", "Weverson", 26, 67, "BR"],
    ["MF", "Pedro Nunes", 23, 66, "PT"],
    ["MF", "Bruno Lourenco", 26, 65, "PT"],
    ["MF", "Joao Simoes", 24, 64, "PT"],
    ["FW", "Rafael Barbosa", 21, 70, "PT"],
    ["FW", "Luis Santos", 22, 68, "PT"],
    ["FW", "Fabiano Silva", 25, 67, "BR"],
    ["FW", "Pedro Malheiro", 24, 66, "PT"],
    ["FW", "Bruno Silva", 24, 65, "PT"],
    ["FW", "Jorge Pereira", 25, 64, "PT"],
    ["FW", "Renato Santos", 23, 63, "PT"],
  ],
  vizela: [
    ["GK", "Fabijan Buntic", 28, 71, "HR"],
    ["GK", "Bruno Varela", 29, 67, "PT"],
    ["GK", "Joao Goncalves", 22, 64, "PT"],
    ["DF", "Bruno Gaspar", 31, 70, "PT"],
    ["DF", "Miguel Magalhaes", 24, 69, "PT"],
    ["DF", "Joao Ferreira", 25, 68, "PT"],
    ["DF", "Pedro Silva", 23, 67, "PT"],
    ["DF", "Bruno Silva", 24, 66, "PT"],
    ["DF", "Tiago Ferraz", 26, 65, "PT"],
    ["MF", "Samu Oliveira", 27, 70, "PT"],
    ["MF", "Kiki Afonso", 25, 69, "PT"],
    ["MF", "Nuno Moreira", 24, 68, "PT"],
    ["MF", "Fabio Carvalho", 23, 67, "PT"],
    ["MF", "Pedro Nunes", 24, 66, "PT"],
    ["MF", "Bruno Lourenco", 26, 65, "PT"],
    ["MF", "Joao Simoes", 24, 64, "PT"],
    ["FW", "Osman Bukari", 25, 72, "GH"],
    ["FW", "Fabio Silva", 23, 68, "PT"],
    ["FW", "Renato Santos", 23, 67, "PT"],
    ["FW", "Luis Santos", 22, 66, "PT"],
    ["FW", "Tiago Gouveia", 23, 65, "PT"],
    ["FW", "Goncalo Rodrigues", 24, 64, "PT"],
    ["FW", "Pedro Amador", 25, 63, "PT"],
  ],
  chaves: [
    ["GK", "Ricardo Nunes", 28, 70, "PT"],
    ["GK", "Bruno Nunes", 25, 66, "PT"],
    ["GK", "Tiago Sousa", 23, 63, "PT"],
    ["DF", "Joao Marcelo", 22, 69, "PT"],
    ["DF", "Pedro Chaves", 24, 68, "PT"],
    ["DF", "Bruno Antunes", 27, 67, "PT"],
    ["DF", "Tiago Silva", 26, 66, "PT"],
    ["DF", "Fabio Cardoso", 23, 65, "PT"],
    ["DF", "Renato Santos", 24, 64, "PT"],
    ["MF", "David Simao", 30, 69, "PT"],
    ["MF", "Pedro Nunes", 24, 68, "PT"],
    ["MF", "Bruno Lourenco", 26, 67, "PT"],
    ["MF", "Joao Simoes", 24, 66, "PT"],
    ["MF", "Tiago Gouveia", 23, 65, "PT"],
    ["MF", "Goncalo Rodrigues", 24, 64, "PT"],
    ["MF", "Pedro Amador", 25, 63, "PT"],
    ["FW", "Roberto Fernandez", 22, 68, "PY"],
    ["FW", "Rafael Braga", 21, 67, "PT"],
    ["FW", "Luis Santos", 22, 66, "PT"],
    ["FW", "Fabiano Silva", 25, 65, "BR"],
    ["FW", "Bruno Silva", 24, 64, "PT"],
    ["FW", "Jorge Pereira", 25, 63, "PT"],
    ["FW", "Pedro Malheiro", 24, 62, "PT"],
  ],
  casa: [
    ["GK", "Giovani", 28, 71, "BR"],
    ["GK", "Bruno Varela", 29, 67, "PT"],
    ["GK", "Joao Goncalves", 22, 64, "PT"],
    ["DF", "Cuca", 26, 69, "PT"],
    ["DF", "Joao Marcelo", 22, 68, "PT"],
    ["DF", "Pedro Chaves", 24, 67, "PT"],
    ["DF", "Bruno Antunes", 27, 66, "PT"],
    ["DF", "Tiago Silva", 26, 65, "PT"],
    ["DF", "Fabio Cardoso", 23, 64, "PT"],
    ["MF", "Tomas Ribeiro", 25, 70, "PT"],
    ["MF", "Alan Ruiz", 28, 69, "AR"],
    ["MF", "Pedro Nunes", 24, 68, "PT"],
    ["MF", "Bruno Lourenco", 26, 67, "PT"],
    ["MF", "Joao Simoes", 24, 66, "PT"],
    ["MF", "Tiago Gouveia", 23, 65, "PT"],
    ["MF", "Goncalo Rodrigues", 24, 64, "PT"],
    ["FW", "Rafael Braga", 21, 68, "PT"],
    ["FW", "Luis Santos", 22, 67, "PT"],
    ["FW", "Fabiano Silva", 25, 66, "BR"],
    ["FW", "Bruno Silva", 24, 65, "PT"],
    ["FW", "Renato Santos", 23, 64, "PT"],
    ["FW", "Pedro Amador", 25, 63, "PT"],
    ["FW", "Pedro Malheiro", 24, 62, "PT"],
  ],
  portimon: [
    ["GK", "Koke", 32, 70, "ES"],
    ["GK", "Bruno Nunes", 25, 66, "PT"],
    ["GK", "Tiago Sousa", 23, 63, "PT"],
    ["DF", "Pedro Rosario", 25, 68, "PT"],
    ["DF", "Joao Marcelo", 22, 67, "PT"],
    ["DF", "Bruno Antunes", 27, 66, "PT"],
    ["DF", "Tiago Silva", 26, 65, "PT"],
    ["DF", "Fabio Cardoso", 23, 64, "PT"],
    ["DF", "Renato Santos", 24, 63, "PT"],
    ["MF", "David Simao", 30, 67, "PT"],
    ["MF", "Pedro Nunes", 24, 66, "PT"],
    ["MF", "Bruno Lourenco", 26, 65, "PT"],
    ["MF", "Joao Simoes", 24, 64, "PT"],
    ["MF", "Tiago Gouveia", 23, 63, "PT"],
    ["MF", "Goncalo Rodrigues", 24, 62, "PT"],
    ["MF", "Pedro Amador", 25, 61, "PT"],
    ["FW", "Rafael Braga", 21, 66, "PT"],
    ["FW", "Luis Santos", 22, 65, "PT"],
    ["FW", "Fabiano Silva", 25, 64, "BR"],
    ["FW", "Bruno Silva", 24, 63, "PT"],
    ["FW", "Pedro Malheiro", 24, 61, "PT"],
    ["FW", "Pedro Chaves", 24, 60, "PT"],
    ["FW", "Jorge Pereira", 25, 59, "PT"],
  ],
  farense: [
    ["GK", "Claudio Falcao", 27, 69, "PT"],
    ["GK", "Bruno Nunes", 25, 65, "PT"],
    ["GK", "Tiago Sousa", 23, 62, "PT"],
    ["DF", "Gustavo Lopes", 22, 67, "PT"],
    ["DF", "Joao Marcelo", 22, 66, "PT"],
    ["DF", "Bruno Antunes", 27, 65, "PT"],
    ["DF", "Tiago Silva", 26, 64, "PT"],
    ["DF", "Fabio Cardoso", 23, 63, "PT"],
    ["DF", "Renato Santos", 24, 62, "PT"],
    ["MF", "David Simao", 30, 66, "PT"],
    ["MF", "Pedro Nunes", 24, 65, "PT"],
    ["MF", "Bruno Lourenco", 26, 64, "PT"],
    ["MF", "Joao Simoes", 24, 63, "PT"],
    ["MF", "Tiago Gouveia", 23, 62, "PT"],
    ["MF", "Goncalo Rodrigues", 24, 61, "PT"],
    ["MF", "Pedro Amador", 25, 60, "PT"],
    ["FW", "Rafael Braga", 21, 65, "PT"],
    ["FW", "Luis Santos", 22, 64, "PT"],
    ["FW", "Fabiano Silva", 25, 63, "BR"],
    ["FW", "Bruno Silva", 24, 62, "PT"],
    ["FW", "Pedro Malheiro", 24, 61, "PT"],
    ["FW", "Pedro Chaves", 24, 60, "PT"],
    ["FW", "Pedro Rosario", 25, 59, "PT"],
  ],
  moreirense: [
    ["GK", "Caio Secco", 26, 72, "BR"],
    ["GK", "Bruno Nunes", 25, 68, "PT"],
    ["GK", "Tiago Sousa", 23, 65, "PT"],
    ["DF", "Marcelo", 28, 71, "BR"],
    ["DF", "Joao Marcelo", 22, 70, "PT"],
    ["DF", "Bruno Antunes", 27, 69, "PT"],
    ["DF", "Tiago Silva", 26, 68, "PT"],
    ["DF", "Fabio Cardoso", 23, 67, "PT"],
    ["DF", "Renato Santos", 24, 66, "PT"],
    ["MF", "Alan Ruiz", 28, 71, "AR"],
    ["MF", "Pedro Nunes", 24, 70, "PT"],
    ["MF", "Bruno Lourenco", 26, 69, "PT"],
    ["MF", "Joao Simoes", 24, 68, "PT"],
    ["MF", "Tiago Gouveia", 23, 67, "PT"],
    ["MF", "Goncalo Rodrigues", 24, 66, "PT"],
    ["MF", "Pedro Amador", 25, 65, "PT"],
    ["FW", "Rafael Braga", 21, 70, "PT"],
    ["FW", "Luis Santos", 22, 69, "PT"],
    ["FW", "Fabiano Silva", 25, 68, "BR"],
    ["FW", "Bruno Silva", 24, 67, "PT"],
    ["FW", "Pedro Malheiro", 24, 66, "PT"],
    ["FW", "Pedro Chaves", 24, 65, "PT"],
    ["FW", "Pedro Rosario", 25, 64, "PT"],
  ],
};
