/** @type {Record<string, Array<[string, string, number, number, string?]>>} */
export default {
  hilal: [
    ["GK", "Yassine Bono", 33, 82, "MA"],
    ["GK", "Khalid Al-Owais", 33, 74, "SA"],
    ["GK", "Mohammed Al-Owais", 33, 73, "SA"],
    ["DF", "Kalidou Koulibaly", 33, 84, "SN"],
    ["DF", "Ali Al-Bulaihi", 35, 78, "SA"],
    ["DF", "Renan Lodi", 26, 80, "BR"],
    ["DF", "Yazeed Al-Shahrani", 32, 76, "SA"],
    ["DF", "Mohamed Kanno", 30, 77, "SA"],
    ["DF", "Hasan Tambakti", 26, 74, "SA"],
    ["DF", "Nasser Al-Dawsari", 25, 75, "SA"],
    ["DF", "Ali Lajami", 27, 73, "SA"],
    ["MF", "Ruben Neves", 27, 85, "PT"],
    ["MF", "Salem Al-Dawsari", 33, 80, "SA"],
    ["MF", "Malcom", 27, 83, "BR"],
    ["MF", "Sergej Milinkovic-Savic", 29, 84, "RS"],
    ["MF", "Salman Al-Faraj", 35, 77, "SA"],
    ["MF", "Abdullah Al-Khaibari", 27, 74, "SA"],
    ["MF", "Musab Al-Juwair", 21, 72, "SA"],
    ["FW", "Aleksandar Mitrovic", 29, 84, "RS"],
    ["FW", "Michael", 28, 79, "BR"],
    ["FW", "Neymar", 33, 86, "BR"],
    ["FW", "Abdullah Al-Hamdan", 25, 74, "SA"],
    ["FW", "Abdulrahman Al-Aboud", 28, 73, "SA"],
  ],
  nassr: [
    ["GK", "David Ospina", 36, 78, "CO"],
    ["GK", "Raghed Al-Najjar", 26, 72, "SA"],
    ["GK", "Nawaf Al-Abed", 33, 70, "SA"],
    ["DF", "Aymeric Laporte", 30, 83, "ES"],
    ["DF", "Sultan Al-Ghannam", 30, 76, "SA"],
    ["DF", "Ali Lajami", 27, 75, "SA"],
    ["DF", "Abdulelah Al-Amri", 27, 74, "SA"],
    ["DF", "Nawaf Boushal", 24, 72, "SA"],
    ["DF", "Mohammed Al-Fatil", 31, 73, "SA"],
    ["DF", "Wesley", 30, 74, "BR"],
    ["MF", "Otavio", 29, 83, "PT"],
    ["MF", "Anderson Talisca", 30, 82, "BR"],
    ["MF", "Marcelo Brozovic", 31, 83, "HR"],
    ["MF", "Ali Al-Hassan", 26, 74, "SA"],
    ["MF", "Abdulmajeed Al-Sulayhim", 29, 73, "SA"],
    ["MF", "Ayman Yahya", 23, 72, "SA"],
    ["MF", "Abdulrahman Al-Aboud", 28, 72, "SA"],
    ["FW", "Cristiano Ronaldo", 39, 87, "PT"],
    ["FW", "Angelo Gabriel", 19, 76, "BR"],
    ["FW", "Sadio Mane", 32, 84, "SN"],
    ["FW", "Abdulrahman Ghareeb", 27, 74, "SA"],
    ["FW", "Giovani", 28, 73, "BR"],
    ["FW", "Mano", 27, 72, "BR"],
  ],
  ittihad: [
    ["GK", "Marcelo Grohe", 37, 76, "BR"],
    ["GK", "Abdullah Al-Jadaani", 27, 72, "SA"],
    ["GK", "Abdulrahman Al-Sanbi", 25, 70, "SA"],
    ["DF", "Fabinho", 31, 83, "BR"],
    ["DF", "Ahmed Sharahili", 28, 74, "SA"],
    ["DF", "Ziyad Al-Sahafi", 30, 73, "SA"],
    ["DF", "Madallah Al-Olayan", 26, 72, "SA"],
    ["DF", "Ahmed Hegazi", 33, 76, "EG"],
    ["DF", "Hassan Kadish", 28, 71, "SA"],
    ["DF", "Abdulelah Al-Amri", 27, 72, "SA"],
    ["MF", "N'Golo Kante", 33, 84, "FR"],
    ["MF", "Jota", 25, 78, "PT"],
    ["MF", "Saleh Al-Shehri", 31, 75, "SA"],
    ["MF", "Farouq Mussa", 24, 73, "SA"],
    ["MF", "Haroun Camara", 22, 72, "GN"],
    ["MF", "Abdulrahman Al-Aboud", 28, 71, "SA"],
    ["MF", "Ahmed Abdu", 25, 70, "SA"],
    ["FW", "Karim Benzema", 37, 86, "FR"],
    ["FW", "Romarinho", 33, 78, "BR"],
    ["FW", "Abdulfattah Adam", 24, 75, "SA"],
    ["FW", "Odion Ighalo", 35, 76, "NG"],
    ["FW", "Fahad Al-Muwallad", 30, 74, "SA"],
    ["FW", "Ahmed Al-Naqel", 26, 72, "SA"],
  ],
  ahli: [
    ["GK", "Eduard Mendy", 32, 82, "SN"],
    ["GK", "Abdullah Al-Muaiqel", 30, 72, "SA"],
    ["GK", "Mohammed Al-Rubaie", 27, 70, "SA"],
    ["DF", "Roger Ibañez", 25, 79, "BR"],
    ["DF", "Ziyad Al-Sahafi", 30, 73, "SA"],
    ["DF", "Yahya Al-Shehri", 34, 74, "SA"],
    ["DF", "Abdulelah Al-Amri", 27, 73, "SA"],
    ["DF", "Motaz Hawsawi", 28, 72, "SA"],
    ["DF", "Ziyad Al-Ahmari", 26, 71, "SA"],
    ["DF", "Mohammed Al-Breik", 29, 70, "SA"],
    ["MF", "Franck Kessie", 27, 82, "CI"],
    ["MF", "Riyad Mahrez", 33, 84, "DZ"],
    ["MF", "Abdulrahman Ghareeb", 27, 74, "SA"],
    ["MF", "Saleh Al-Amri", 25, 73, "SA"],
    ["MF", "Ezequiel Fernandez", 22, 72, "AR"],
    ["MF", "Sumayhan Al-Nabit", 24, 71, "SA"],
    ["MF", "Fahad Al-Ghamdi", 26, 70, "SA"],
    ["FW", "Roberto Firmino", 32, 83, "BR"],
    ["FW", "Talisca", 30, 80, "BR"],
    ["FW", "Fahad Al-Muwallad", 30, 78, "SA"],
    ["FW", "Abdullah Al-Johani", 28, 76, "SA"],
    ["FW", "Ahmed Abdu", 25, 74, "SA"],
    ["FW", "Odion Ighalo", 35, 75, "NG"],
  ],
  shabab: [
    ["GK", "Seung-Gyu Kim", 34, 76, "KR"],
    ["GK", "Abdullah Al-Owaishir", 28, 71, "SA"],
    ["GK", "Mohammed Al-Rubaie", 27, 69, "SA"],
    ["DF", "Hassan Kadish", 28, 73, "SA"],
    ["DF", "Abdulelah Al-Amri", 27, 72, "SA"],
    ["DF", "Motaz Hawsawi", 28, 71, "SA"],
    ["DF", "Ziyad Al-Ahmari", 26, 70, "SA"],
    ["DF", "Ahmed Sharahili", 28, 69, "SA"],
    ["DF", "Madallah Al-Olayan", 26, 68, "SA"],
    ["DF", "Mohammed Al-Breik", 29, 67, "SA"],
    ["MF", "Ever Banega", 36, 78, "AR"],
    ["MF", "Saleh Al-Amri", 25, 71, "SA"],
    ["MF", "Abdulrahman Al-Aboud", 28, 70, "SA"],
    ["MF", "Ahmed Abdu", 25, 69, "SA"],
    ["MF", "Farouq Mussa", 24, 68, "SA"],
    ["MF", "Haroun Camara", 22, 67, "GN"],
    ["MF", "Fahad Al-Ghamdi", 26, 66, "SA"],
    ["FW", "Carlos Vinicius", 29, 77, "BR"],
    ["FW", "Saleh Al-Shehri", 31, 75, "SA"],
    ["FW", "Abdulfattah Adam", 24, 73, "SA"],
    ["FW", "Odion Ighalo", 35, 74, "NG"],
    ["FW", "Fahad Al-Muwallad", 30, 72, "SA"],
    ["FW", "Ahmed Al-Naqel", 26, 71, "SA"],
  ],
  ettifaq: [
    ["GK", "Paulo Victor", 28, 74, "BR"],
    ["GK", "Abdullah Al-Jadaani", 27, 70, "SA"],
    ["GK", "Mohammed Al-Rubaie", 27, 68, "SA"],
    ["DF", "Jack Hendrick", 22, 73, "EN"],
    ["DF", "Abdulelah Al-Amri", 27, 72, "SA"],
    ["DF", "Motaz Hawsawi", 28, 71, "SA"],
    ["DF", "Ziyad Al-Ahmari", 26, 70, "SA"],
    ["DF", "Ahmed Sharahili", 28, 69, "SA"],
    ["DF", "Madallah Al-Olayan", 26, 68, "SA"],
    ["DF", "Mohammed Al-Breik", 29, 67, "SA"],
    ["MF", "Jordan Henderson", 34, 80, "EN"],
    ["MF", "Georginio Wijnaldum", 33, 79, "NL"],
    ["MF", "Abdulrahman Al-Aboud", 28, 72, "SA"],
    ["MF", "Ahmed Abdu", 25, 71, "SA"],
    ["MF", "Farouq Mussa", 24, 70, "SA"],
    ["MF", "Haroun Camara", 22, 69, "GN"],
    ["MF", "Saleh Al-Amri", 25, 68, "SA"],
    ["FW", "Moussa Dembele", 28, 78, "FR"],
    ["FW", "Joao Pedro", 22, 76, "BR"],
    ["FW", "Abdulfattah Adam", 24, 74, "SA"],
    ["FW", "Odion Ighalo", 35, 73, "NG"],
    ["FW", "Fahad Al-Muwallad", 30, 72, "SA"],
    ["FW", "Ahmed Al-Naqel", 26, 71, "SA"],
  ],
  fateh: [
    ["GK", "Vladimir Stojkovic", 36, 74, "RS"],
    ["GK", "Abdullah Al-Owaishir", 28, 70, "SA"],
    ["GK", "Mohammed Al-Rubaie", 27, 68, "SA"],
    ["DF", "Abdulelah Al-Amri", 27, 72, "SA"],
    ["DF", "Motaz Hawsawi", 28, 71, "SA"],
    ["DF", "Ziyad Al-Ahmari", 26, 70, "SA"],
    ["DF", "Ahmed Sharahili", 28, 69, "SA"],
    ["DF", "Madallah Al-Olayan", 26, 68, "SA"],
    ["DF", "Hassan Kadish", 28, 67, "SA"],
    ["DF", "Mohammed Al-Breik", 29, 66, "SA"],
    ["MF", "Christian Cueva", 32, 75, "PE"],
    ["MF", "Abdulrahman Al-Aboud", 28, 72, "SA"],
    ["MF", "Ahmed Abdu", 25, 71, "SA"],
    ["MF", "Farouq Mussa", 24, 70, "SA"],
    ["MF", "Haroun Camara", 22, 69, "GN"],
    ["MF", "Saleh Al-Amri", 25, 68, "SA"],
    ["MF", "Fahad Al-Ghamdi", 26, 67, "SA"],
    ["FW", "Matheus Pereira", 28, 76, "BR"],
    ["FW", "Abdulfattah Adam", 24, 73, "SA"],
    ["FW", "Odion Ighalo", 35, 72, "NG"],
    ["FW", "Fahad Al-Muwallad", 30, 71, "SA"],
    ["FW", "Ahmed Al-Naqel", 26, 70, "SA"],
    ["FW", "Saleh Al-Shehri", 31, 69, "SA"],
  ],
  taawon: [
    ["GK", "Joao Pinheiro", 28, 73, "PT"],
    ["GK", "Abdullah Al-Owaishir", 28, 69, "SA"],
    ["GK", "Mohammed Al-Rubaie", 27, 67, "SA"],
    ["DF", "Abdulelah Al-Amri", 27, 71, "SA"],
    ["DF", "Motaz Hawsawi", 28, 70, "SA"],
    ["DF", "Ziyad Al-Ahmari", 26, 69, "SA"],
    ["DF", "Ahmed Sharahili", 28, 68, "SA"],
    ["DF", "Madallah Al-Olayan", 26, 67, "SA"],
    ["DF", "Hassan Kadish", 28, 66, "SA"],
    ["DF", "Mohammed Al-Breik", 29, 65, "SA"],
    ["MF", "Anderson Talisca", 30, 77, "BR"],
    ["MF", "Abdulrahman Al-Aboud", 28, 71, "SA"],
    ["MF", "Ahmed Abdu", 25, 70, "SA"],
    ["MF", "Farouq Mussa", 24, 69, "SA"],
    ["MF", "Haroun Camara", 22, 68, "GN"],
    ["MF", "Saleh Al-Amri", 25, 67, "SA"],
    ["MF", "Fahad Al-Ghamdi", 26, 66, "SA"],
    ["FW", "Abdulfattah Adam", 24, 72, "SA"],
    ["FW", "Odion Ighalo", 35, 71, "NG"],
    ["FW", "Fahad Al-Muwallad", 30, 70, "SA"],
    ["FW", "Ahmed Al-Naqel", 26, 69, "SA"],
    ["FW", "Saleh Al-Shehri", 31, 68, "SA"],
    ["FW", "Carlos Vinicius", 29, 67, "BR"],
  ],
  khaleej: [
    ["GK", "Mateus", 27, 72, "BR"],
    ["GK", "Abdullah Al-Owaishir", 28, 68, "SA"],
    ["GK", "Mohammed Al-Rubaie", 27, 66, "SA"],
    ["DF", "Abdulelah Al-Amri", 27, 70, "SA"],
    ["DF", "Motaz Hawsawi", 28, 69, "SA"],
    ["DF", "Ziyad Al-Ahmari", 26, 68, "SA"],
    ["DF", "Ahmed Sharahili", 28, 67, "SA"],
    ["DF", "Madallah Al-Olayan", 26, 66, "SA"],
    ["DF", "Hassan Kadish", 28, 65, "SA"],
    ["DF", "Mohammed Al-Breik", 29, 64, "SA"],
    ["MF", "Fabio Martins", 31, 72, "PT"],
    ["MF", "Abdulrahman Al-Aboud", 28, 69, "SA"],
    ["MF", "Ahmed Abdu", 25, 68, "SA"],
    ["MF", "Farouq Mussa", 24, 67, "SA"],
    ["MF", "Haroun Camara", 22, 66, "GN"],
    ["MF", "Saleh Al-Amri", 25, 65, "SA"],
    ["MF", "Fahad Al-Ghamdi", 26, 64, "SA"],
    ["FW", "Abdulfattah Adam", 24, 70, "SA"],
    ["FW", "Odion Ighalo", 35, 69, "NG"],
    ["FW", "Fahad Al-Muwallad", 30, 68, "SA"],
    ["FW", "Ahmed Al-Naqel", 26, 67, "SA"],
    ["FW", "Saleh Al-Shehri", 31, 66, "SA"],
    ["FW", "Carlos Vinicius", 29, 65, "BR"],
  ],
  fayha: [
    ["GK", "Vladimir Stojkovic", 36, 71, "RS"],
    ["GK", "Abdullah Al-Owaishir", 28, 67, "SA"],
    ["GK", "Mohammed Al-Rubaie", 27, 65, "SA"],
    ["DF", "Abdulelah Al-Amri", 27, 69, "SA"],
    ["DF", "Motaz Hawsawi", 28, 68, "SA"],
    ["DF", "Ziyad Al-Ahmari", 26, 67, "SA"],
    ["DF", "Ahmed Sharahili", 28, 66, "SA"],
    ["DF", "Madallah Al-Olayan", 26, 65, "SA"],
    ["DF", "Hassan Kadish", 28, 64, "SA"],
    ["DF", "Mohammed Al-Breik", 29, 63, "SA"],
    ["MF", "Paulo Vitor", 28, 70, "BR"],
    ["MF", "Abdulrahman Al-Aboud", 28, 68, "SA"],
    ["MF", "Ahmed Abdu", 25, 67, "SA"],
    ["MF", "Farouq Mussa", 24, 66, "SA"],
    ["MF", "Haroun Camara", 22, 65, "GN"],
    ["MF", "Saleh Al-Amri", 25, 64, "SA"],
    ["MF", "Fahad Al-Ghamdi", 26, 63, "SA"],
    ["FW", "Abdulfattah Adam", 24, 68, "SA"],
    ["FW", "Odion Ighalo", 35, 67, "NG"],
    ["FW", "Fahad Al-Muwallad", 30, 66, "SA"],
    ["FW", "Ahmed Al-Naqel", 26, 65, "SA"],
    ["FW", "Saleh Al-Shehri", 31, 64, "SA"],
    ["FW", "Carlos Vinicius", 29, 63, "BR"],
  ],
  raed: [
    ["GK", "Mateus", 27, 71, "BR"],
    ["GK", "Abdullah Al-Owaishir", 28, 67, "SA"],
    ["GK", "Mohammed Al-Rubaie", 27, 65, "SA"],
    ["DF", "Abdulelah Al-Amri", 27, 68, "SA"],
    ["DF", "Motaz Hawsawi", 28, 67, "SA"],
    ["DF", "Ziyad Al-Ahmari", 26, 66, "SA"],
    ["DF", "Ahmed Sharahili", 28, 65, "SA"],
    ["DF", "Madallah Al-Olayan", 26, 64, "SA"],
    ["DF", "Hassan Kadish", 28, 63, "SA"],
    ["DF", "Mohammed Al-Breik", 29, 62, "SA"],
    ["MF", "Amir Sayoud", 29, 69, "DZ"],
    ["MF", "Abdulrahman Al-Aboud", 28, 67, "SA"],
    ["MF", "Ahmed Abdu", 25, 66, "SA"],
    ["MF", "Farouq Mussa", 24, 65, "SA"],
    ["MF", "Haroun Camara", 22, 64, "GN"],
    ["MF", "Saleh Al-Amri", 25, 63, "SA"],
    ["MF", "Fahad Al-Ghamdi", 26, 62, "SA"],
    ["FW", "Abdulfattah Adam", 24, 67, "SA"],
    ["FW", "Odion Ighalo", 35, 66, "NG"],
    ["FW", "Fahad Al-Muwallad", 30, 65, "SA"],
    ["FW", "Ahmed Al-Naqel", 26, 64, "SA"],
    ["FW", "Saleh Al-Shehri", 31, 63, "SA"],
    ["FW", "Carlos Vinicius", 29, 62, "BR"],
  ],
  damac: [
    ["GK", "Abdullah Al-Jadaani", 27, 70, "SA"],
    ["GK", "Abdullah Al-Owaishir", 28, 66, "SA"],
    ["GK", "Mohammed Al-Rubaie", 27, 64, "SA"],
    ["DF", "Abdulelah Al-Amri", 27, 67, "SA"],
    ["DF", "Motaz Hawsawi", 28, 66, "SA"],
    ["DF", "Ziyad Al-Ahmari", 26, 65, "SA"],
    ["DF", "Ahmed Sharahili", 28, 64, "SA"],
    ["DF", "Madallah Al-Olayan", 26, 63, "SA"],
    ["DF", "Hassan Kadish", 28, 62, "SA"],
    ["DF", "Mohammed Al-Breik", 29, 61, "SA"],
    ["MF", "Georges-Kevin Nkoudou", 29, 72, "CM"],
    ["MF", "Abdulrahman Al-Aboud", 28, 66, "SA"],
    ["MF", "Ahmed Abdu", 25, 65, "SA"],
    ["MF", "Farouq Mussa", 24, 64, "SA"],
    ["MF", "Haroun Camara", 22, 63, "GN"],
    ["MF", "Saleh Al-Amri", 25, 62, "SA"],
    ["MF", "Fahad Al-Ghamdi", 26, 61, "SA"],
    ["FW", "Abdulfattah Adam", 24, 66, "SA"],
    ["FW", "Odion Ighalo", 35, 65, "NG"],
    ["FW", "Fahad Al-Muwallad", 30, 64, "SA"],
    ["FW", "Ahmed Al-Naqel", 26, 63, "SA"],
    ["FW", "Saleh Al-Shehri", 31, 62, "SA"],
    ["FW", "Carlos Vinicius", 29, 61, "BR"],
  ],
  abha: [
    ["GK", "Mateus", 27, 69, "BR"],
    ["GK", "Abdullah Al-Owaishir", 28, 65, "SA"],
    ["GK", "Mohammed Al-Rubaie", 27, 63, "SA"],
    ["DF", "Abdulelah Al-Amri", 27, 66, "SA"],
    ["DF", "Motaz Hawsawi", 28, 65, "SA"],
    ["DF", "Ziyad Al-Ahmari", 26, 64, "SA"],
    ["DF", "Ahmed Sharahili", 28, 63, "SA"],
    ["DF", "Madallah Al-Olayan", 26, 62, "SA"],
    ["DF", "Hassan Kadish", 28, 61, "SA"],
    ["DF", "Mohammed Al-Breik", 29, 60, "SA"],
    ["MF", "Ciprian Tatarusanu", 38, 70, "RO"],
    ["MF", "Abdulrahman Al-Aboud", 28, 65, "SA"],
    ["MF", "Ahmed Abdu", 25, 64, "SA"],
    ["MF", "Farouq Mussa", 24, 63, "SA"],
    ["MF", "Haroun Camara", 22, 62, "GN"],
    ["MF", "Saleh Al-Amri", 25, 61, "SA"],
    ["MF", "Fahad Al-Ghamdi", 26, 60, "SA"],
    ["FW", "Abdulfattah Adam", 24, 65, "SA"],
    ["FW", "Odion Ighalo", 35, 64, "NG"],
    ["FW", "Fahad Al-Muwallad", 30, 63, "SA"],
    ["FW", "Ahmed Al-Naqel", 26, 62, "SA"],
    ["FW", "Saleh Al-Shehri", 31, 61, "SA"],
    ["FW", "Carlos Vinicius", 29, 60, "BR"],
  ],
  akhdoud: [
    ["GK", "Abdullah Al-Jadaani", 27, 68, "SA"],
    ["GK", "Abdullah Al-Owaishir", 28, 64, "SA"],
    ["GK", "Mohammed Al-Rubaie", 27, 62, "SA"],
    ["DF", "Abdulelah Al-Amri", 27, 65, "SA"],
    ["DF", "Motaz Hawsawi", 28, 64, "SA"],
    ["DF", "Ziyad Al-Ahmari", 26, 63, "SA"],
    ["DF", "Ahmed Sharahili", 28, 62, "SA"],
    ["DF", "Madallah Al-Olayan", 26, 61, "SA"],
    ["DF", "Hassan Kadish", 28, 60, "SA"],
    ["DF", "Mohammed Al-Breik", 29, 59, "SA"],
    ["MF", "Kévin N'Doram", 28, 69, "FR"],
    ["MF", "Abdulrahman Al-Aboud", 28, 64, "SA"],
    ["MF", "Ahmed Abdu", 25, 63, "SA"],
    ["MF", "Farouq Mussa", 24, 62, "SA"],
    ["MF", "Haroun Camara", 22, 61, "GN"],
    ["MF", "Saleh Al-Amri", 25, 60, "SA"],
    ["MF", "Fahad Al-Ghamdi", 26, 59, "SA"],
    ["FW", "Abdulfattah Adam", 24, 64, "SA"],
    ["FW", "Odion Ighalo", 35, 63, "NG"],
    ["FW", "Fahad Al-Muwallad", 30, 62, "SA"],
    ["FW", "Ahmed Al-Naqel", 26, 61, "SA"],
    ["FW", "Saleh Al-Shehri", 31, 60, "SA"],
    ["FW", "Carlos Vinicius", 29, 59, "BR"],
  ],
  hazem: [
    ["GK", "Mateus", 27, 67, "BR"],
    ["GK", "Abdullah Al-Owaishir", 28, 63, "SA"],
    ["GK", "Mohammed Al-Rubaie", 27, 61, "SA"],
    ["DF", "Abdulelah Al-Amri", 27, 64, "SA"],
    ["DF", "Motaz Hawsawi", 28, 63, "SA"],
    ["DF", "Ziyad Al-Ahmari", 26, 62, "SA"],
    ["DF", "Ahmed Sharahili", 28, 61, "SA"],
    ["DF", "Madallah Al-Olayan", 26, 60, "SA"],
    ["DF", "Hassan Kadish", 28, 59, "SA"],
    ["DF", "Mohammed Al-Breik", 29, 58, "SA"],
    ["MF", "Anthony Stokes", 35, 68, "IE"],
    ["MF", "Abdulrahman Al-Aboud", 28, 63, "SA"],
    ["MF", "Ahmed Abdu", 25, 62, "SA"],
    ["MF", "Farouq Mussa", 24, 61, "SA"],
    ["MF", "Haroun Camara", 22, 60, "GN"],
    ["MF", "Saleh Al-Amri", 25, 59, "SA"],
    ["MF", "Fahad Al-Ghamdi", 26, 58, "SA"],
    ["FW", "Abdulfattah Adam", 24, 63, "SA"],
    ["FW", "Odion Ighalo", 35, 62, "NG"],
    ["FW", "Fahad Al-Muwallad", 30, 61, "SA"],
    ["FW", "Ahmed Al-Naqel", 26, 60, "SA"],
    ["FW", "Saleh Al-Shehri", 31, 59, "SA"],
    ["FW", "Carlos Vinicius", 29, 58, "BR"],
  ],
  riyadh: [
    ["GK", "Abdullah Al-Jadaani", 27, 66, "SA"],
    ["GK", "Abdullah Al-Owaishir", 28, 62, "SA"],
    ["GK", "Mohammed Al-Rubaie", 27, 60, "SA"],
    ["DF", "Abdulelah Al-Amri", 27, 63, "SA"],
    ["DF", "Motaz Hawsawi", 28, 62, "SA"],
    ["DF", "Ziyad Al-Ahmari", 26, 61, "SA"],
    ["DF", "Ahmed Sharahili", 28, 60, "SA"],
    ["DF", "Madallah Al-Olayan", 26, 59, "SA"],
    ["DF", "Hassan Kadish", 28, 58, "SA"],
    ["DF", "Mohammed Al-Breik", 29, 57, "SA"],
    ["MF", "Cristian Tello", 32, 72, "ES"],
    ["MF", "Abdulrahman Al-Aboud", 28, 62, "SA"],
    ["MF", "Ahmed Abdu", 25, 61, "SA"],
    ["MF", "Farouq Mussa", 24, 60, "SA"],
    ["MF", "Haroun Camara", 22, 59, "GN"],
    ["MF", "Saleh Al-Amri", 25, 58, "SA"],
    ["MF", "Fahad Al-Ghamdi", 26, 57, "SA"],
    ["FW", "Abdulfattah Adam", 24, 62, "SA"],
    ["FW", "Odion Ighalo", 35, 61, "NG"],
    ["FW", "Fahad Al-Muwallad", 30, 60, "SA"],
    ["FW", "Ahmed Al-Naqel", 26, 59, "SA"],
    ["FW", "Saleh Al-Shehri", 31, 58, "SA"],
    ["FW", "Carlos Vinicius", 29, 57, "BR"],
  ],
};
