/** @type {Record<string, Array<[string, string, number, number, string?]>>} */
export default {
  whobear: [
    ["GK", "Thibaut Courtois", 33, 90, "BE"],
    ["GK", "Andriy Lunin", 26, 82, "UA"],
    ["DF", "Antonio Rudiger", 31, 87, "DE"],
    ["DF", "Eder Militao", 26, 86, "BR"],
    ["DF", "Ferland Mendy", 29, 83, "FR"],
    ["DF", "Dani Carvajal", 32, 85, "ES"],
    ["DF", "David Alaba", 32, 84, "AT"],
    ["DF", "Fran Garcia", 25, 79, "ES"],
    ["DF", "Dean Huijsen", 19, 76, "ES"],
    ["MF", "Federico Valverde", 26, 89, "UY"],
    ["MF", "Jude Bellingham", 22, 90, "EN"],
    ["MF", "Aurélien Tchouameni", 25, 86, "FR"],
    ["MF", "Eduardo Camavinga", 22, 85, "FR"],
    ["MF", "Luka Modric", 39, 85, "HR"],
    ["MF", "Dani Ceballos", 28, 81, "ES"],
    ["MF", "Arda Guler", 19, 78, "TR"],
    ["FW", "Vinicius Junior", 24, 90, "BR"],
    ["FW", "Rodrygo", 23, 86, "BR"],
    ["FW", "Kylian Mbappe", 26, 92, "FR"],
    ["FW", "Endrick", 18, 77, "BR"],
    ["FW", "Brahim Diaz", 25, 82, "MA"],
    ["DF", "Trent Alexander-Arnold", 26, 87, "EN"],
    ["MF", "Franco Mastantuono", 17, 72, "AR"],
  ],
  barbeat: [
    ["GK", "Marc-Andre ter Stegen", 33, 88, "DE"],
    ["GK", "Wojciech Szczesny", 35, 82, "PL"],
    ["DF", "Jules Kounde", 26, 86, "FR"],
    ["DF", "Ronald Araujo", 25, 85, "UY"],
    ["DF", "Alejandro Balde", 21, 82, "ES"],
    ["DF", "Inigo Martinez", 33, 82, "ES"],
    ["DF", "Andreas Christensen", 28, 83, "DK"],
    ["DF", "Joao Cancelo", 30, 84, "PT"],
    ["DF", "Hector Fort", 18, 72, "ES"],
    ["MF", "Pedri", 22, 89, "ES"],
    ["MF", "Gavi", 20, 85, "ES"],
    ["MF", "Frenkie de Jong", 27, 86, "NL"],
    ["MF", "Fermin Lopez", 21, 80, "ES"],
    ["MF", "Marc Bernal", 17, 74, "ES"],
    ["MF", "Dani Olmo", 26, 86, "ES"],
    ["FW", "Robert Lewandowski", 36, 88, "PL"],
    ["FW", "Raphinha", 28, 86, "BR"],
    ["FW", "Lamine Yamal", 17, 84, "ES"],
    ["FW", "Ferran Torres", 24, 82, "ES"],
    ["FW", "Ansu Fati", 22, 78, "ES"],
    ["FW", "Pau Victor", 23, 76, "ES"],
    ["MF", "Pablo Torre", 21, 75, "ES"],
    ["DF", "Eric Garcia", 23, 78, "ES"],
  ],
  rojiblanco: [
    ["GK", "Jan Oblak", 32, 89, "SI"],
    ["GK", "Jose Maria Gimenez", 30, 78, "UY"],
    ["DF", "Jose Gimenez", 30, 84, "UY"],
    ["DF", "Robin Le Normand", 28, 84, "ES"],
    ["DF", "Reinildo Mandava", 30, 80, "MZ"],
    ["DF", "Nahuel Molina", 27, 82, "AR"],
    ["DF", "Marcos Llorente", 29, 84, "ES"],
    ["DF", "Cesar Azpilicueta", 35, 78, "ES"],
    ["DF", "Clément Lenglet", 29, 80, "FR"],
    ["MF", "Koke", 32, 84, "ES"],
    ["MF", "Rodrigo De Paul", 30, 84, "AR"],
    ["MF", "Marcos Llorente", 29, 84, "ES"],
    ["MF", "Pablo Barrios", 21, 82, "ES"],
    ["MF", "Thomas Lemar", 29, 80, "FR"],
    ["MF", "Conor Gallagher", 24, 82, "EN"],
    ["FW", "Antoine Griezmann", 34, 87, "FR"],
    ["FW", "Julian Alvarez", 25, 85, "AR"],
    ["FW", "Alexander Sorloth", 28, 82, "NO"],
    ["FW", "Samuel Lino", 25, 80, "BR"],
    ["FW", "Angel Correa", 29, 82, "AR"],
    ["FW", "Giuliano Simeone", 22, 76, "AR"],
    ["MF", "Javi Galan", 29, 78, "ES"],
    ["DF", "Axel Witsel", 35, 79, "BE"],
  ],
  seville: [
    ["GK", "Orjan Nyland", 34, 76, "NO"],
    ["GK", "Alfon", 21, 72, "ES"],
    ["DF", "Loic Badé", 24, 79, "FR"],
    ["DF", "Marcao", 28, 78, "BR"],
    ["DF", "Gonzalo Montiel", 27, 79, "AR"],
    ["DF", "Adrià Pedrosa", 26, 78, "ES"],
    ["DF", "Tanguy Nianzou", 22, 76, "FR"],
    ["DF", "Kike Salas", 23, 77, "ES"],
    ["DF", "Nemanja Gudelj", 33, 77, "RS"],
    ["MF", "Ivan Rakitic", 36, 82, "HR"],
    ["MF", "Suso", 31, 80, "ES"],
    ["MF", "Lucien Agoume", 22, 77, "FR"],
    ["MF", "Albert Sambi Lokonga", 24, 78, "BE"],
    ["MF", "Djibril Sow", 27, 79, "CH"],
    ["MF", "Manu Bueno", 20, 74, "ES"],
    ["FW", "Isaac Romero", 24, 77, "ES"],
    ["FW", "Chidera Ejuke", 26, 78, "NG"],
    ["FW", "Dodi Lukebakio", 27, 80, "BE"],
    ["FW", "Peque Fernandez", 21, 75, "ES"],
    ["FW", "Stanis Idumbo", 20, 73, "BE"],
    ["FW", "Juanlu Sanchez", 21, 76, "ES"],
    ["MF", "Saúl Niguez", 30, 79, "ES"],
    ["DF", "Oso", 22, 72, "ES"],
  ],
  bat: [
    ["GK", "Giorgi Mamardashvili", 24, 82, "GE"],
    ["GK", "Diego Lopez", 22, 73, "ES"],
    ["DF", "Cristhian Mosquera", 20, 76, "ES"],
    ["DF", "Cesar Tárrega", 22, 75, "ES"],
    ["DF", "Jose Luis Gaya", 29, 81, "ES"],
    ["DF", "Dimitri Foulquier", 31, 76, "FR"],
    ["DF", "Copete", 25, 77, "ES"],
    ["DF", "Yarek Gasiorowski", 20, 74, "ES"],
    ["DF", "Jesus Vazquez", 22, 75, "ES"],
    ["MF", "Pepelu", 27, 80, "ES"],
    ["MF", "Javi Guerra", 21, 79, "ES"],
    ["MF", "Andre Almeida", 24, 78, "PT"],
    ["MF", "Fran Perez", 22, 76, "ES"],
    ["MF", "Luis Rioja", 31, 77, "ES"],
    ["MF", "Hugo Guillamon", 24, 76, "ES"],
    ["FW", "Hugo Duro", 24, 79, "ES"],
    ["FW", "Diego Lopez", 22, 76, "ES"],
    ["FW", "Alberto Marí", 24, 75, "ES"],
    ["FW", "Luis Rioja", 31, 77, "ES"],
    ["FW", "Rafa Mir", 27, 77, "ES"],
    ["FW", "Umar Sadiq", 27, 78, "NG"],
    ["MF", "Eray Comert", 26, 75, "CH"],
    ["DF", "Cristian Rivero", 26, 72, "ES"],
  ],
  lion: [
    ["GK", "Unai Simon", 27, 84, "ES"],
    ["GK", "Julen Agirrezabala", 24, 76, "ES"],
    ["DF", "Yeray Alvarez", 29, 81, "ES"],
    ["DF", "Dani Vivian", 25, 82, "ES"],
    ["DF", "Yuri Berchiche", 34, 79, "ES"],
    ["DF", "Oscar de Marcos", 35, 78, "ES"],
    ["DF", "Lekue", 31, 76, "ES"],
    ["DF", "Imanol Garcia", 22, 75, "ES"],
    ["DF", "Paredes", 24, 77, "ES"],
    ["MF", "Oihan Sancet", 24, 83, "ES"],
    ["MF", "Mikel Vesga", 31, 79, "ES"],
    ["MF", "Unai Gomez", 21, 77, "ES"],
    ["MF", "Ander Herrera", 35, 78, "ES"],
    ["MF", "Ruiz de Galarreta", 31, 78, "ES"],
    ["MF", "Benat Prados", 22, 75, "ES"],
    ["FW", "Inaki Williams", 30, 83, "GH"],
    ["FW", "Nico Williams", 22, 84, "ES"],
    ["FW", "Gorka Guruzeta", 28, 79, "ES"],
    ["FW", "Asier Villalibre", 23, 75, "ES"],
    ["FW", "Berenguer", 29, 78, "ES"],
    ["FW", "Marco Lopez", 20, 73, "ES"],
    ["MF", "Jauregizar", 20, 74, "ES"],
    ["DF", "Egiluz", 21, 72, "ES"],
  ],
  sociedad: [
    ["GK", "Alex Remiro", 29, 83, "ES"],
    ["GK", "Mathew Ryan", 33, 76, "AU"],
    ["DF", "Igor Zubeldia", 27, 81, "ES"],
    ["DF", "Robin Le Normand", 28, 84, "ES"],
    ["DF", "Aihen Munoz", 27, 79, "ES"],
    ["DF", "Hamari Traore", 32, 78, "ML"],
    ["DF", "Sergio Gomez", 23, 78, "ES"],
    ["DF", "Aramburu", 22, 74, "ES"],
    ["DF", "Odriozola", 28, 77, "ES"],
    ["MF", "Mikel Merino", 28, 84, "ES"],
    ["MF", "Martin Zubimendi", 25, 85, "ES"],
    ["MF", "Brais Mendez", 27, 82, "ES"],
    ["MF", "Takefusa Kubo", 23, 82, "JP"],
    ["MF", "Beñat Turrientes", 22, 76, "ES"],
    ["MF", "Pablo Marin", 21, 74, "ES"],
    ["FW", "Mikel Oyarzabal", 28, 84, "ES"],
    ["FW", "Sheraldo Becker", 29, 80, "SR"],
    ["FW", "Barrenetxea", 22, 79, "ES"],
    ["FW", "Carlos Fernandez", 28, 78, "ES"],
    ["FW", "Orriols", 20, 73, "ES"],
    ["FW", "Karrikaburu", 22, 75, "ES"],
    ["MF", "Gorosabel", 28, 76, "ES"],
    ["DF", "Pacheco", 23, 72, "ES"],
  ],
  villar: [
    ["GK", "Diego Conde", 25, 78, "ES"],
    ["GK", "Filip Jorgensen", 22, 76, "DK"],
    ["DF", "Rafa Marin", 22, 78, "ES"],
    ["DF", "Raul Albiol", 39, 79, "ES"],
    ["DF", "Pedraza", 28, 78, "ES"],
    ["DF", "Foyth", 26, 81, "AR"],
    ["DF", "Mandi", 33, 78, "DZ"],
    ["DF", "Kiko Femenia", 33, 76, "ES"],
    ["DF", "Mosquera", 24, 77, "ES"],
    ["MF", "Dani Parejo", 35, 83, "ES"],
    ["MF", "Santi Comesana", 28, 79, "ES"],
    ["MF", "Baena", 23, 82, "ES"],
    ["MF", "Capoue", 36, 78, "FR"],
    ["MF", "Terrats", 24, 77, "ES"],
    ["MF", "Gueye", 25, 78, "SN"],
    ["FW", "Gerard Moreno", 32, 83, "ES"],
    ["FW", "Nicolas Pepe", 29, 80, "CI"],
    ["FW", "Ilias Akhomach", 20, 77, "MA"],
    ["FW", "Danjuma", 28, 79, "NL"],
    ["FW", "Pascu", 20, 74, "ES"],
    ["FW", "Moleiro", 20, 76, "ES"],
    ["MF", "Trigueros", 33, 77, "ES"],
    ["DF", "Cuenca", 24, 75, "ES"],
  ],
  betis: [
    ["GK", "Adrian", 37, 78, "ES"],
    ["GK", "Bravo", 24, 74, "ES"],
    ["DF", "Natan", 24, 78, "BR"],
    ["DF", "Bartra", 33, 80, "ES"],
    ["DF", "Sabaly", 31, 79, "SN"],
    ["DF", "Perraud", 27, 78, "FR"],
    ["DF", "Ruibal", 28, 77, "ES"],
    ["DF", "Miranda", 25, 76, "ES"],
    ["DF", "Pezzella", 33, 78, "AR"],
    ["MF", "Isco", 32, 83, "ES"],
    ["MF", "Guido Rodriguez", 30, 82, "AR"],
    ["MF", "William Carvalho", 32, 81, "PT"],
    ["MF", "Fornals", 28, 80, "ES"],
    ["MF", "Altimira", 21, 76, "ES"],
    ["MF", "Rodri", 24, 77, "ES"],
    ["FW", "Antony", 24, 82, "BR"],
    ["FW", "Abde", 23, 78, "MA"],
    ["FW", "Bakambu", 33, 77, "CD"],
    ["FW", "Juanmi", 31, 78, "ES"],
    ["FW", "Chimy Avila", 30, 77, "AR"],
    ["FW", "Aitor Ruibal", 28, 77, "ES"],
    ["MF", "Lo Celso", 28, 83, "AR"],
    ["DF", "Sidi", 21, 72, "ES"],
  ],
  celta: [
    ["GK", "Vicente Guaita", 37, 79, "ES"],
    ["GK", "Villar", 23, 73, "ES"],
    ["DF", "Carlos Dominguez", 23, 77, "ES"],
    ["DF", "Starfelt", 29, 78, "SE"],
    ["DF", "Jailson", 28, 77, "BR"],
    ["DF", "Mingueza", 25, 77, "ES"],
    ["DF", "Ristic", 28, 76, "RS"],
    ["DF", "Aidoo", 24, 76, "GH"],
    ["DF", "Manu Sanchez", 24, 76, "ES"],
    ["MF", "Beltran", 23, 79, "ES"],
    ["MF", "Alfon", 21, 76, "ES"],
    ["MF", "Swedberg", 20, 76, "SE"],
    ["MF", "Doubt", 28, 75, "PT"],
    ["MF", "De la Torre", 26, 77, "US"],
    ["MF", "Sotelo", 21, 74, "ES"],
    ["FW", "Iago Aspas", 37, 82, "ES"],
    ["FW", "Larsen", 26, 79, "NO"],
    ["FW", "Allende", 25, 77, "AR"],
    ["FW", "Borja Iglesias", 31, 78, "ES"],
    ["FW", "Williot Swedberg", 20, 76, "SE"],
    ["FW", "Alonso", 22, 74, "ES"],
    ["MF", "Cervi", 30, 75, "PT"],
    ["DF", "Mihaila", 22, 72, "RO"],
  ],
  girona: [
    ["GK", "Gazzaniga", 32, 79, "AR"],
    ["GK", "Siebe Van der Hove", 22, 72, "BE"],
    ["DF", "Blind", 34, 78, "NL"],
    ["DF", "Juanpe", 33, 77, "ES"],
    ["DF", "Arnau Martinez", 21, 78, "ES"],
    ["DF", "Miguel Gutierrez", 23, 80, "ES"],
    ["DF", "Krejci", 25, 77, "CZ"],
    ["DF", "Francisco", 21, 74, "ES"],
    ["DF", "Lopez", 24, 76, "ES"],
    ["MF", "Aleix Garcia", 27, 82, "ES"],
    ["MF", "Martin", 25, 78, "ES"],
    ["MF", "Herrera", 26, 76, "ES"],
    ["MF", "Solomon", 25, 79, "IL"],
    ["MF", "Van de Beek", 27, 78, "NL"],
    ["MF", "Gil", 24, 76, "ES"],
    ["FW", "Dovbyk", 27, 83, "UA"],
    ["FW", "Stuani", 38, 77, "UY"],
    ["FW", "Tsygankov", 27, 81, "UA"],
    ["FW", "Misehouy", 19, 74, "NL"],
    ["FW", "Portu", 32, 77, "ES"],
    ["FW", "Asprilla", 22, 75, "CO"],
    ["MF", "Roca", 23, 75, "ES"],
    ["DF", "Valencia", 21, 72, "ES"],
  ],
  mallorca: [
    ["GK", "Rajkovic", 29, 79, "RS"],
    ["GK", "Greif", 27, 74, "SK"],
    ["DF", "Valjent", 29, 78, "SK"],
    ["DF", "Copete", 25, 77, "ES"],
    ["DF", "Raillo", 33, 77, "ES"],
    ["DF", "Maffeo", 27, 78, "AR"],
    ["DF", "Lato", 26, 76, "ES"],
    ["DF", "Costa", 30, 75, "ES"],
    ["DF", "Gonzalez", 24, 75, "ES"],
    ["MF", "Morlanes", 25, 77, "ES"],
    ["MF", "Samu Costa", 24, 78, "PT"],
    ["MF", "Darder", 31, 80, "ES"],
    ["MF", "Mascarell", 31, 77, "DE"],
    ["MF", "Agard", 24, 74, "JM"],
    ["MF", "Dominguez", 21, 73, "ES"],
    ["FW", "Abdon", 33, 76, "BR"],
    ["FW", "Larin", 29, 77, "CA"],
    ["FW", "Muriqi", 30, 80, "XK"],
    ["FW", "Rodriguez", 25, 76, "UY"],
    ["FW", "Navarro", 22, 74, "ES"],
    ["FW", "Latasa", 23, 75, "ES"],
    ["MF", "Valery", 24, 75, "ES"],
    ["DF", "Nastasic", 31, 76, "RS"],
  ],
  getafe: [
    ["GK", "Soria", 31, 79, "ES"],
    ["GK", "David Concha", 27, 72, "ES"],
    ["DF", "Djené", 32, 78, "TG"],
    ["DF", "Duarte", 29, 78, "ES"],
    ["DF", "Aldretti", 33, 76, "ES"],
    ["DF", "Iglesias", 26, 77, "ES"],
    ["DF", "Mitrovic", 35, 76, "RS"],
    ["DF", "Rico", 31, 77, "ES"],
    ["DF", "Carmona", 22, 75, "ES"],
    ["MF", "Arambarri", 29, 79, "UY"],
    ["MF", "Milla", 30, 78, "ES"],
    ["MF", "Almada", 23, 81, "AR"],
    ["MF", "Uche", 21, 77, "NG"],
    ["MF", "Latasa", 23, 76, "ES"],
    ["MF", "Aleñá", 26, 77, "ES"],
    ["FW", "Borja Mayoral", 27, 80, "ES"],
    ["FW", "Greenwood", 23, 82, "EN"],
    ["FW", "Jesus Santiago", 21, 74, "ES"],
    ["FW", "Peter", 22, 75, "BR"],
    ["FW", "Juanmi Latasa", 23, 76, "ES"],
    ["FW", "Neyou", 24, 74, "CM"],
    ["MF", "Mauro Arambarri", 29, 79, "UY"],
    ["DF", "Abqar", 25, 76, "MA"],
  ],
  osasuna: [
    ["GK", "Herrera", 34, 79, "ES"],
    ["GK", "Benito", 22, 72, "ES"],
    ["DF", "Catena", 30, 79, "ES"],
    ["DF", "Herrando", 24, 77, "ES"],
    ["DF", "Boyomo", 24, 78, "CM"],
    ["DF", "Mojica", 32, 77, "CO"],
    ["DF", "Areso", 24, 76, "ES"],
    ["DF", "Peña", 32, 76, "ES"],
    ["DF", "Cruz", 22, 74, "ES"],
    ["MF", "Moncayola", 26, 78, "ES"],
    ["MF", "Torró", 30, 78, "ES"],
    ["MF", "Garcia", 26, 77, "ES"],
    ["MF", "Oroz", 22, 77, "ES"],
    ["MF", "Muñoz", 22, 76, "ES"],
    ["MF", "Ruben Garcia", 31, 77, "ES"],
    ["FW", "Budimir", 33, 80, "HR"],
    ["FW", "Garcia", 30, 78, "ES"],
    ["FW", "Barja", 27, 77, "ES"],
    ["FW", "Raul Garcia", 38, 76, "ES"],
    ["FW", "Bretones", 26, 76, "ES"],
    ["FW", "Ilic", 26, 75, "RS"],
    ["MF", "Brasanac", 32, 76, "RS"],
    ["DF", "Vidal", 25, 74, "ES"],
  ],
  rayo: [
    ["GK", "Batalla", 28, 78, "AR"],
    ["GK", "Dimitrievski", 31, 76, "MK"],
    ["DF", "Balliu", 32, 77, "AL"],
    ["DF", "Lejeune", 33, 78, "ES"],
    ["DF", "Espino", 28, 77, "UY"],
    ["DF", "Ratiu", 26, 76, "RO"],
    ["DF", "Mumin", 26, 75, "GH"],
    ["DF", "Pep Chavarria", 24, 75, "ES"],
    ["DF", "Fran Garcia", 25, 77, "ES"],
    ["MF", "Isi Palazon", 29, 80, "ES"],
    ["MF", "Oscar Valentin", 30, 78, "ES"],
    ["MF", "Ciss", 24, 77, "SN"],
    ["MF", "U Lopez", 21, 76, "ES"],
    ["MF", "Trejo", 36, 77, "AR"],
    ["MF", "Alvaro Garcia", 32, 77, "ES"],
    ["FW", "De Tomas", 29, 79, "ES"],
    ["FW", "Camello", 23, 77, "ES"],
    ["FW", "Nteka", 27, 76, "FR"],
    ["FW", "Falcao", 38, 76, "CO"],
    ["FW", "Embarba", 32, 77, "ES"],
    ["FW", "Garcia", 21, 74, "ES"],
    ["MF", "Perez", 25, 75, "ES"],
    ["DF", "Mendy", 22, 72, "SN"],
  ],
  alaves: [
    ["GK", "Sivera", 28, 78, "ES"],
    ["GK", "Owono", 23, 72, "GQ"],
    ["DF", "Gorosabel", 28, 77, "ES"],
    ["DF", "Marin", 26, 76, "ES"],
    ["DF", "Tenaglia", 28, 76, "AR"],
    ["DF", "Sedlar", 28, 76, "HR"],
    ["DF", "Garcia", 24, 75, "ES"],
    ["DF", "Lopez", 23, 74, "ES"],
    ["DF", "Parada", 22, 73, "ES"],
    ["MF", "Guridi", 29, 78, "ES"],
    ["MF", "Benavidez", 26, 77, "AR"],
    ["MF", "Blanco", 25, 76, "ES"],
    ["MF", "Guevara", 27, 77, "ES"],
    ["MF", "Sola", 23, 76, "ES"],
    ["MF", "Rebbach", 26, 75, "DZ"],
    ["FW", "Omorodion", 20, 79, "NG"],
    ["FW", "Villalibre", 23, 76, "ES"],
    ["FW", "Rioja", 31, 77, "ES"],
    ["FW", "Martinez", 25, 76, "AR"],
    ["FW", "Conechny", 26, 76, "AR"],
    ["FW", "Kolarov", 22, 74, "RS"],
    ["MF", "Hagi", 26, 77, "RO"],
    ["DF", "Abqar", 25, 76, "MA"],
  ],
};
